<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */

// Files from packages declared in the admin <scope/>.

// Files declared in the <adminRequire/> section.
require_once dirname(__FILE__).'/../plugins/utils/export/phpexcel/1.7.5/PHPExcel/IOFactory.php';
require_once dirname(__FILE__).'/../plugins/utils/i18n/fine/2.1/FineAdmin.php';
require_once dirname(__FILE__).'/../plugins/utils/i18n/fine/2.1/controllers/EditLabelController.php';
require_once dirname(__FILE__).'/../plugins/utils/i18n/fine/2.1/ValidatorDescriptor.php';
require_once dirname(__FILE__).'/../plugins/utils/i18n/fine/2.1/RegisterSearchModule.php';
require_once dirname(__FILE__).'/../plugins/security/userservice/1.0/MoufUserServiceValidators.php';
require_once dirname(__FILE__).'/../plugins/utils/cache/cache-interface/1.0/admin/CacheAdmin.php';
require_once dirname(__FILE__).'/../plugins/utils/cache/cache-interface/1.0/admin/controllers/PurgeCacheController.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash-common/3.2/SplashCommonAdmin.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash-common/3.2/services/SplashCallback.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash-common/3.2/services/SplashUrlManager.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash-common/3.2/controllers/admin/SplashViewUrlsController.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash/3.2/SplashAdmin.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash/3.2/models/SplashGenerateService.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash/3.2/controllers/admin/SplashAdminApacheConfigureController.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash/3.2/controllers/admin/SplashInstallController.php';

?>
