<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'ROOT_URL' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The ROOT_URL of the Mouf web application. This is the URL, starting and ending with a slash, that you use to access the Mouf administration interface.',
  ),
));

$moufManager->setAllVariables(array (
));

$moufManager->addComponentInstances(array (
  '__anonymous_1351271275513' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BootstrapMenuRenderer',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'fieldProperties' => 
    array (
      'pullRight' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '__anonymous_1351271292292',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous_1351271292292' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'logout2MenuItem',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous_1356167917517' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'type' => 'string',
        'value' => 'vendor/mouf/famfamfam/icons/drive_go.png',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'ajaxinstance' => 
  array (
    'class' => 'Mouf\\Controllers\\MoufAjaxInstanceController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
      'rightBlock' => 'block.right',
    ),
  ),
  'analyzeClassesMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'includePhpFilesMenuItemIcon',
      ),
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Analyze classes',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'includes/',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'apcCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fallback' => 'fileCacheService',
    ),
  ),
  'block.content' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => 'messageWidget',
      ),
    ),
  ),
  'block.footer' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.header' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => 'navBar',
      ),
    ),
  ),
  'block.left' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => 'instanceMenuRenderer',
        1 => 'documentationMenuRenderer',
        2 => 'specialActionsMenuRenderer',
      ),
    ),
  ),
  'block.right' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'bootstrapMessageRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Messages\\BootstrapMessageRenderer',
    'external' => false,
    'weak' => false,
  ),
  'config' => 
  array (
    'class' => 'Mouf\\Controllers\\ConfigController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'configCompleteValidator' => 
  array (
    'class' => 'Mouf\\Validator\\MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Configuration file validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'src/direct/config_complete_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'createNewInstanceMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Create a new instance',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/newInstance2',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'createNewInstanceMenuItemIcon',
      ),
    ),
  ),
  'createNewInstanceMenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/page_add.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'css.moufCssStyles' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManager',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'javascript.underscore',
        1 => 'jQueryLibrary',
        2 => 'jQueryUiLibrary',
        3 => 'javascript.bootstrap',
        4 => 'javascript.syntaxHighlighter',
        5 => 'setRootUrlJsBlock',
        6 => 'javascript.jquery-filetree',
        7 => 'javascript.moufInstanceLibrary',
        8 => 'javascript.composer',
        9 => 'css.moufCssStyles',
        10 => 'javascript.chooseInstancePopupJs',
        11 => 'javascript.jquery-filetree',
        12 => 'messageServiceLibrary',
        13 => 'weblibrary.qtip2',
      	14 => 'javascript.jqBootstrapValidation',
      	15 => 'javascript.highlight.js',
      ),
    ),
  ),
  'defaultWebLibraryRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\DefaultWebLibraryRenderer',
    'external' => false,
  ),
  'displayGraph' => 
  array (
    'class' => 'Mouf\\Controllers\\MoufDisplayGraphController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'displayPhpInfoMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Display PHP Info',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'phpInfo/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'displayPhpInfoMenuItemIcon',
      ),
    ),
  ),
  'displayPhpInfoMenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/table.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'doc' => 
  array (
    'class' => 'Mouf\\Controllers\\DocumentationController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
      'documentationMenu' => 'documentationMenu',
    ),
  ),
  'documentationMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
  ),
  'documentationMenuRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BasicMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'documentationMenu',
    ),
  ),
  'documentationSubMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'viewDocumentationMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Documentation',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '90',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'downloadPackages2MenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Install/Remove packages',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'composer/view',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'downloadPackages2MenuItemIcon',
      ),
    ),
  ),
  'downloadPackages2MenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/download.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'editConfigurationMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Edit configuration',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'config/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'editConfigurationMenuItemIcon',
      ),
    ),
  ),
  'editConfigurationMenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/note_edit.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'errorLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\ErrorLogLogger',
    'external' => false,
    'fieldProperties' => 
    array (
      'level' => 
      array (
        'value' => '4',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fileCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'relativeToSystemTempDirectory' => 
      array (
        'type' => 'string',
        'value' => true,
        'metadata' => 
        array (
        ),
      ),
      'cacheDirectory' => 
      array (
        'type' => 'string',
        'value' => 'mouf_cache',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'includePhpFilesMenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/page_white_php.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'includes' => 
  array (
    'class' => 'Mouf\\Controllers\\IncludesAnalyzerController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'installProcessValidator' => 
  array (
    'class' => 'Mouf\\Validator\\MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Installation process validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'src/direct/install_process_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'installTasksMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'string',
        'value' => 'Installation tasks',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'type' => 'string',
        'value' => 'installer/',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => '__anonymous_1356167917517',
      ),
    ),
  ),
  'installTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\MoufTemplate\\MoufTemplate',
    'external' => false,
    'setterBinds' => 
    array (
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setContent' => 'block.content',
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'src-dev/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'installedPackagesController' => 
  array (
    'class' => 'Mouf\\Controllers\\Composer\\InstalledPackagesController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'installer' => 
  array (
    'class' => 'Mouf\\Controllers\\InstallController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'instance' => 
  array (
    'class' => 'Mouf\\Controllers\\MoufInstanceController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'instanceMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
  ),
  'instanceMenuRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BasicMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'instanceMenu',
    ),
  ),
  'instancesSubMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'viewDeclaredInstancesMenuItem',
        1 => 'createNewInstanceMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Instances',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '30',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'jQueryLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery/jquery-1.11.0.min.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'jQueryUiLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-ui/js/jquery-ui-1.10.2.custom.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-ui/css/ui-lightness/jquery-ui-1.10.2.custom.min.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
  'javascript.bootstrap' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.utils.bootstrap/js/bootstrap.min.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.utils.bootstrap/css/bootstrap.min.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'javascript.chooseInstancePopupJs' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/chooseInstancePopup.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.jqBootstrapValidation' =>
		array (
				'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
				'external' => false,
				'weak' => false,
				'setterProperties' =>
				array (
						'setJsFiles' =>
						array (
								'value' =>
								array (
										0 => 'vendor/mouf/javascript.jquery.jq-bootstrap-validation/lib/jqBootstrapValidation.js',
								),
								'type' => 'string',
								'metadata' =>
								array (
								),
						),
						'setCssFiles' =>
						array (
								'value' => false,
								'type' => 'string',
								'metadata' =>
								array (
								),
						),
				),
		),
  'javascript.composer' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/composer/composer.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.jquery-filetree' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-filetree/jqueryFileTree.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-filetree/jqueryFileTree.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
  'javascript.moufInstanceLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/instances/messages.js',
          1 => 'src-dev/views/instances/utils.js',
          2 => 'src-dev/views/instances/instances.js',
          3 => 'src-dev/views/instances/defaultRenderer.js',
          4 => 'src-dev/views/instances/moufui.js',
          5 => 'src-dev/views/instances/saveManager.js',
          6 => 'src-dev/views/instances/jquery.scrollintoview.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/instances/defaultRenderer.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.syntaxHighlighter' => 
  array (
    'class' => 'Mouf\\Javascript\\SyntaxHighlighterWebLibrary',
    'external' => false,
    'weak' => false,
  ),
  'javascript.topribbonmenu' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.template.menus.topribbonmenu/topribbonmenu.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.template.menus.topribbonmenu/topribbonmenu.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
		'javascript.highlight.js' =>
		array (
				'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
				'external' => false,
				'weak' => false,
				'setterProperties' =>
				array (
						'setJsFiles' =>
						array (
								'value' =>
								array (
										0 => 'src-dev/views/javascript/highlight.js/highlight.pack.js',
								),
								'type' => 'string',
								'metadata' =>
								array (
								),
						),
						'setCssFiles' =>
						array (
								'value' =>
								array (
										0 => 'src-dev/views/javascript/highlight.js/styles/googlecode.css',
								),
								'type' => 'string',
								'metadata' =>
								array (
								),
						),
				),
			),
  'javascript.underscore' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.underscore/lib/underscore-min.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.underscore.debug' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'plugins/javascript/underscore/1.3.3/lib/underscore.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'login' => 
  array (
    'class' => 'Mouf\\Controllers\\MoufLoginController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufLoginTemplate',
      'userService' => 'userService',
      'contentBlock' => 'block.content',
      'contentBeforeLoginBox' => 
      array (
        0 => 'loginWelcomeMessage',
      ),
    ),
    'fieldProperties' => 
    array (
      'defaultRedirectUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoutRedirectUrl' => 
      array (
        'value' => 'login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'loginLabel' => 
      array (
        'value' => 'Login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nLoginLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'passwordLabel' => 
      array (
        'value' => 'Password',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nPasswordLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'loginSubmitLabel' => 
      array (
        'value' => 'Login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nLoginSubmitLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'badCredentialsLabel' => 
      array (
        'value' => 'Invalid login or password, please try again.',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nBadCredentialsLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'loginWelcomeMessage' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlString',
    'external' => false,
    'fieldProperties' => 
    array (
      'Mouf\\Html\\HtmlElement\\HtmlString' => 
      array (
        'value' => '<h1>Login</h1>
<p>Welcome to Mouf. Please login to access the administration interface of your web application.</p>
<br/>
<br/>
<br/>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'logout2MenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Logout',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'login/logout',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'logout2MenuItemIcon',
      ),
    ),
  ),
  'logout2MenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/door_open.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'mainMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'projectSubMenu',
        1 => 'instancesSubMenu',
        2 => 'packagesSubMenu',
      ),
    ),
  ),
  'messageServiceLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.widgets.messageservice/messages.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'messageWidget' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Widget\\MessageWidget',
    'external' => false,
    'fieldBinds' => 
    array (
      'messageProvider' => 'userMessageService',
      'messageRenderer' => 'bootstrapMessageRenderer',
    ),
  ),
  'miscellaneousSubMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'moufStatus2MenuItem',
        1 => 'displayPhpInfoMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Miscellaneous',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '100',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'mouf' => 
  array (
    'class' => 'Mouf\\Controllers\\MoufController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'moufInstallController' => 
  array (
    'class' => 'Mouf\\Controllers\\MoufInstallController',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
    ),
    'fieldBinds' => 
    array (
      'template' => 'moufInstallTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'moufInstallTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'setterBinds' => 
    array (
      'setFooter' => 'block.footer',
      'setRight' => 'block.right',
      'setContent' => 'block.content',
      'setWebLibraryManager' => 'defaultWebLibraryManager',
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'src-dev/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufInstallTemplate2' => 
  array (
    'class' => 'Mouf\\Html\\Template\\MoufTemplate\\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'src-dev/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufLoginTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setFooter' => 'block.footer',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setContent' => 'block.content',
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'src-dev/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'enableResponsiveDesign' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLeftColumnSize' => 
      array (
        'value' => '3',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setRightColumnSize' => 
      array (
        'value' => '2',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setTitle' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setWrapLeftSideBarInWell' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setWrapRightSideBarInWell' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufStatus2MenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Mouf Status',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'validate/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'moufStatus2MenuItemIcon',
      ),
    ),
  ),
  'moufStatus2MenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/tick.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setContent' => 'block.content',
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'src-dev/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'enableResponsiveDesign' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLeftColumnSize' => 
      array (
        'value' => '3',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setRightColumnSize' => 
      array (
        'value' => '2',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setTitle' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setWrapLeftSideBarInWell' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setWrapRightSideBarInWell' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufTemplate.bak' => 
  array (
    'class' => 'Mouf\\Html\\Template\\MoufTemplate\\MoufTemplate',
    'external' => false,
    'setterBinds' => 
    array (
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setContent' => 'block.content',
      'setWebLibraryManager' => 'defaultWebLibraryManager',
    ),
    'weak' => false,
    'fieldProperties' => 
    array (
      'favIconUrl' => 
      array (
        'value' => 'plugins/html/template/MoufTemplate/1.0/images/favicon.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoImg' => 
      array (
        'value' => 'src-dev/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'navBar' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BootstrapNavBar',
    'external' => false,
    'weak' => true,
    'fieldProperties' => 
    array (
      'inverted' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'navBarMenuRenderer',
          1 => '__anonymous_1351271275513',
          2 => 'searchBox',
          3 => 'purgeCodeCacheButton',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'anonymous' => false,
  ),
  'navBarMenuRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BootstrapMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'mainMenu',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldProperties' => 
    array (
      'inverted' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'pullRight' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagesSubMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
    ),
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '10',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Packages',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 
        array (
          0 => 'downloadPackages2MenuItem',
          1 => 'installTasksMenuItem',
          2 => 'viewDocumentationMenuItem',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'phpInfo' => 
  array (
    'class' => 'Mouf\\Controllers\\PhpInfoController',
    'external' => false,
  ),
  'phpProjectSubMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'editConfigurationMenuItem',
        1 => 'analyzeClassesMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'PHP Project',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '20',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'projectSubMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'editConfigurationMenuItem',
        1 => 'analyzeClassesMenuItem',
        2 => 'moufStatus2MenuItem',
        3 => 'displayPhpInfoMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Project',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '0',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'purgeCodeCacheButton' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'string',
        'value' => 'src-dev/views/codeCacheButton.php',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootController' => 
  array (
    'class' => 'Mouf\\Controllers\\MoufRootController',
    'external' => false,
  ),
  'rootUrlJsFile' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'string',
        'value' => 'src-dev/views/instances/setRootUrlBlock.php',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'search' => 
  array (
    'class' => 'Mouf\\Controllers\\SearchController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
      'searchService' => 'searchService',
    ),
  ),
  'searchBox' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'fieldProperties' => 
    array (
      'fileName' => 
      array (
        'value' => 'src-dev/views/search/searchbox.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'relativeToRootPath' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'searchService' => 
  array (
    'class' => 'Mouf\\MoufSearchService',
    'external' => false,
    'fieldBinds' => 
    array (
      'searchableServices' => 
      array (
        0 => 'mouf',
      ),
    ),
  ),
  'sessionManager' => 
  array (
    'class' => 'Mouf\\Utils\\Session\\SessionManager\\DefaultSessionManager',
    'external' => false,
  ),
  'setRootUrlJsBlock' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\InlineWebLibrary',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'additionalElement' => 'rootUrlJsFile',
    ),
  ),
  'specialActionsMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
  ),
  'specialActionsMenuRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BasicMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'specialActionsMenu',
    ),
  ),
  'splash' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Splash',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
      'defaultTemplate' => 'moufTemplate',
      'content' => 'block.content',
      'http404Handler' => 'splash.errorsController',
      'http500Handler' => 'splash.errorsController',
    ),
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'supportsHttps' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splash.errorsController' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
    ),
  ),
  'splashBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
  ),
  'splashTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'plugins/mvc/splash-common/3.2/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'splashBrowserLanguageDetection',
    ),
  ),
  'userFileDao' => 
  array (
    'class' => 'Mouf\\Security\\UserFileDao\\UserFileDao',
    'external' => false,
    'fieldProperties' => 
    array (
      'userFile' => 
      array (
        'value' => '../../../mouf/no_commit/MoufUsers.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userMessageService' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Service\\SessionMessageService',
    'external' => false,
    'fieldBinds' => 
    array (
      'sessionManager' => 'sessionManager',
    ),
  ),
  'userService' => 
  array (
    'class' => 'Mouf\\Security\\UserService\\UserService',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
      'userDao' => 'userFileDao',
    ),
    'fieldProperties' => 
    array (
      'loginPageUrl' => 
      array (
        'value' => 'login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'sessionPrefix' => 
      array (
        'value' => 'Mouf',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'redirectParameter' => 
      array (
        'value' => 'redirect',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validate' => 
  array (
    'class' => 'Mouf\\Controllers\\MoufValidatorController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'contentBlock' => 'block.content',
      'validatorService' => 'validatorService',
    ),
  ),
  'validatorService' => 
  array (
    'class' => 'Mouf\\Validator\\MoufValidatorService',
    'external' => false,
    'fieldBinds' => 
    array (
      'validators' => 
      array (
        0 => 'installProcessValidator',
        1 => 'configCompleteValidator',
      ),
    ),
  ),
  'viewDeclaredInstancesMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'View declared instances',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'viewDeclaredInstancesMenuItemIcon',
      ),
    ),
  ),
  'viewDeclaredInstancesMenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/page_white_stack.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'viewDocumentationMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'View packages documentation',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'doc/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'viewDocumentationMenuItemIcon',
      ),
    ),
  ),
  'viewDocumentationMenuItemIcon' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'src-dev/views/images/report.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'weblibrary.qtip2' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/javascript/qtip/jquery.qtip.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'src-dev/views/javascript/qtip/jquery.qtip.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
));


unset($moufManager);

/**
				* This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
				* This object can be used to get the objects manage by MOUF.
				*
				*/
				class MoufAdmin {
					/**
	 * @return Mouf\Controllers\MoufAjaxInstanceController
	 */
	 public static function getAjaxinstance() {
	 	return MoufManager::getMoufManager()->getInstance('ajaxinstance');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getAnalyzeClassesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('analyzeClassesMenuItem');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getApcCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('apcCacheService');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_content() {
	 	return MoufManager::getMoufManager()->getInstance('block.content');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_footer() {
	 	return MoufManager::getMoufManager()->getInstance('block.footer');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_header() {
	 	return MoufManager::getMoufManager()->getInstance('block.header');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_left() {
	 	return MoufManager::getMoufManager()->getInstance('block.left');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_right() {
	 	return MoufManager::getMoufManager()->getInstance('block.right');
	 }

	/**
	 * @return Mouf\Html\Template\Messages\BootstrapMessageRenderer
	 */
	 public static function getBootstrapMessageRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('bootstrapMessageRenderer');
	 }

	/**
	 * @return Mouf\Controllers\ConfigController
	 */
	 public static function getConfig() {
	 	return MoufManager::getMoufManager()->getInstance('config');
	 }

	/**
	 * @return Mouf\Validator\MoufBasicValidationProvider
	 */
	 public static function getConfigCompleteValidator() {
	 	return MoufManager::getMoufManager()->getInstance('configCompleteValidator');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getCreateNewInstanceMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('createNewInstanceMenuItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getCreateNewInstanceMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('createNewInstanceMenuItemIcon');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getCss_moufCssStyles() {
	 	return MoufManager::getMoufManager()->getInstance('css.moufCssStyles');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryManager');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\DefaultWebLibraryRenderer
	 */
	 public static function getDefaultWebLibraryRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryRenderer');
	 }

	/**
	 * @return Mouf\Controllers\MoufDisplayGraphController
	 */
	 public static function getDisplayGraph() {
	 	return MoufManager::getMoufManager()->getInstance('displayGraph');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getDisplayPhpInfoMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('displayPhpInfoMenuItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getDisplayPhpInfoMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('displayPhpInfoMenuItemIcon');
	 }

	/**
	 * @return Mouf\Controllers\DocumentationController
	 */
	 public static function getDoc() {
	 	return MoufManager::getMoufManager()->getInstance('doc');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\Menu
	 */
	 public static function getDocumentationMenu() {
	 	return MoufManager::getMoufManager()->getInstance('documentationMenu');
	 }

	/**
	 * @return Mouf\Html\Template\Menus\BasicMenuRenderer
	 */
	 public static function getDocumentationMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('documentationMenuRenderer');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getDocumentationSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('documentationSubMenu');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getDownloadPackages2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('downloadPackages2MenuItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getDownloadPackages2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('downloadPackages2MenuItemIcon');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getEditConfigurationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('editConfigurationMenuItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getEditConfigurationMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('editConfigurationMenuItemIcon');
	 }

	/**
	 * @return Mouf\Utils\Log\ErrorLogLogger
	 */
	 public static function getErrorLogger() {
	 	return MoufManager::getMoufManager()->getInstance('errorLogger');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getFileCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('fileCacheService');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getIncludePhpFilesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('includePhpFilesMenuItemIcon');
	 }

	/**
	 * @return Mouf\Controllers\IncludesAnalyzerController
	 */
	 public static function getIncludes() {
	 	return MoufManager::getMoufManager()->getInstance('includes');
	 }

	/**
	 * @return Mouf\Validator\MoufBasicValidationProvider
	 */
	 public static function getInstallProcessValidator() {
	 	return MoufManager::getMoufManager()->getInstance('installProcessValidator');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getInstallTasksMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('installTasksMenuItem');
	 }

	/**
	 * @return Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getInstallTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('installTemplate');
	 }

	/**
	 * @return Mouf\Controllers\Composer\InstalledPackagesController
	 */
	 public static function getInstalledPackagesController() {
	 	return MoufManager::getMoufManager()->getInstance('installedPackagesController');
	 }

	/**
	 * @return Mouf\Controllers\InstallController
	 */
	 public static function getInstaller() {
	 	return MoufManager::getMoufManager()->getInstance('installer');
	 }

	/**
	 * @return Mouf\Controllers\MoufInstanceController
	 */
	 public static function getInstance() {
	 	return MoufManager::getMoufManager()->getInstance('instance');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\Menu
	 */
	 public static function getInstanceMenu() {
	 	return MoufManager::getMoufManager()->getInstance('instanceMenu');
	 }

	/**
	 * @return Mouf\Html\Template\Menus\BasicMenuRenderer
	 */
	 public static function getInstanceMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('instanceMenuRenderer');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getInstancesSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('instancesSubMenu');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryUiLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryUiLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_bootstrap() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.bootstrap');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_chooseInstancePopupJs() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.chooseInstancePopupJs');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_composer() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.composer');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_jqueryfiletree() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.jquery-filetree');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_moufInstanceLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.moufInstanceLibrary');
	 }

	/**
	 * @return Mouf\Javascript\SyntaxHighlighterWebLibrary
	 */
	 public static function getJavascript_syntaxHighlighter() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.syntaxHighlighter');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_topribbonmenu() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.topribbonmenu');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_underscore() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.underscore');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_underscore_debug() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.underscore.debug');
	 }

	/**
	 * @return Mouf\Controllers\MoufLoginController
	 */
	 public static function getLogin() {
	 	return MoufManager::getMoufManager()->getInstance('login');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlString
	 */
	 public static function getLoginWelcomeMessage() {
	 	return MoufManager::getMoufManager()->getInstance('loginWelcomeMessage');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getLogout2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('logout2MenuItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getLogout2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('logout2MenuItemIcon');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\Menu
	 */
	 public static function getMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('mainMenu');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getMessageServiceLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('messageServiceLibrary');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Widget\MessageWidget
	 */
	 public static function getMessageWidget() {
	 	return MoufManager::getMoufManager()->getInstance('messageWidget');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getMiscellaneousSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('miscellaneousSubMenu');
	 }

	/**
	 * @return Mouf\Controllers\MoufController
	 */
	 public static function getMouf() {
	 	return MoufManager::getMoufManager()->getInstance('mouf');
	 }

	/**
	 * @return Mouf\Controllers\MoufInstallController
	 */
	 public static function getMoufInstallController() {
	 	return MoufManager::getMoufManager()->getInstance('moufInstallController');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getMoufInstallTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufInstallTemplate');
	 }

	/**
	 * @return Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getMoufInstallTemplate2() {
	 	return MoufManager::getMoufManager()->getInstance('moufInstallTemplate2');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getMoufLoginTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufLoginTemplate');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getMoufStatus2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('moufStatus2MenuItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getMoufStatus2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('moufStatus2MenuItemIcon');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getMoufTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufTemplate');
	 }

	/**
	 * @return Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getMoufTemplate_bak() {
	 	return MoufManager::getMoufManager()->getInstance('moufTemplate.bak');
	 }

	/**
	 * @return Mouf\Html\Template\Menus\BootstrapNavBar
	 */
	 public static function getNavBar() {
	 	return MoufManager::getMoufManager()->getInstance('navBar');
	 }

	/**
	 * @return Mouf\Html\Template\Menus\BootstrapMenuRenderer
	 */
	 public static function getNavBarMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('navBarMenuRenderer');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getPackagesSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('packagesSubMenu');
	 }

	/**
	 * @return Mouf\Controllers\PhpInfoController
	 */
	 public static function getPhpInfo() {
	 	return MoufManager::getMoufManager()->getInstance('phpInfo');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getPhpProjectSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('phpProjectSubMenu');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getProjectSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('projectSubMenu');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlFromFile
	 */
	 public static function getPurgeCodeCacheButton() {
	 	return MoufManager::getMoufManager()->getInstance('purgeCodeCacheButton');
	 }

	/**
	 * @return Mouf\Validator\MoufBasicValidationProvider
	 */
	 public static function getRequiredFilesValidator() {
	 	return MoufManager::getMoufManager()->getInstance('requiredFilesValidator');
	 }

	/**
	 * @return Mouf\Controllers\MoufRootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->getInstance('rootController');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlFromFile
	 */
	 public static function getRootUrlJsFile() {
	 	return MoufManager::getMoufManager()->getInstance('rootUrlJsFile');
	 }

	/**
	 * @return Mouf\Controllers\SearchController
	 */
	 public static function getSearch() {
	 	return MoufManager::getMoufManager()->getInstance('search');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlFromFile
	 */
	 public static function getSearchBox() {
	 	return MoufManager::getMoufManager()->getInstance('searchBox');
	 }

	/**
	 * @return Mouf\MoufSearchService
	 */
	 public static function getSearchService() {
	 	return MoufManager::getMoufManager()->getInstance('searchService');
	 }

	/**
	 * @return Mouf\Utils\Session\SessionManager\DefaultSessionManager
	 */
	 public static function getSessionManager() {
	 	return MoufManager::getMoufManager()->getInstance('sessionManager');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\InlineWebLibrary
	 */
	 public static function getSetRootUrlJsBlock() {
	 	return MoufManager::getMoufManager()->getInstance('setRootUrlJsBlock');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\Menu
	 */
	 public static function getSpecialActionsMenu() {
	 	return MoufManager::getMoufManager()->getInstance('specialActionsMenu');
	 }

	/**
	 * @return Mouf\Html\Template\Menus\BasicMenuRenderer
	 */
	 public static function getSpecialActionsMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('specialActionsMenuRenderer');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Splash
	 */
	 public static function getSplash() {
	 	return MoufManager::getMoufManager()->getInstance('splash');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\HttpErrorsController
	 */
	 public static function getSplash_errorsController() {
	 	return MoufManager::getMoufManager()->getInstance('splash.errorsController');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getSplashBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->getInstance('splashBrowserLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getSplashTranslateService() {
	 	return MoufManager::getMoufManager()->getInstance('splashTranslateService');
	 }

	/**
	 * @return Mouf\Security\UserFileDao\UserFileDao
	 */
	 public static function getUserFileDao() {
	 	return MoufManager::getMoufManager()->getInstance('userFileDao');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Service\SessionMessageService
	 */
	 public static function getUserMessageService() {
	 	return MoufManager::getMoufManager()->getInstance('userMessageService');
	 }

	/**
	 * @return Mouf\Security\UserService\UserService
	 */
	 public static function getUserService() {
	 	return MoufManager::getMoufManager()->getInstance('userService');
	 }

	/**
	 * @return Mouf\Controllers\MoufValidatorController
	 */
	 public static function getValidate() {
	 	return MoufManager::getMoufManager()->getInstance('validate');
	 }

	/**
	 * @return Mouf\Validator\MoufValidatorService
	 */
	 public static function getValidatorService() {
	 	return MoufManager::getMoufManager()->getInstance('validatorService');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getViewDeclaredInstancesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('viewDeclaredInstancesMenuItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getViewDeclaredInstancesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('viewDeclaredInstancesMenuItemIcon');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getViewDocumentationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('viewDocumentationMenuItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItemStyleIcon
	 */
	 public static function getViewDocumentationMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('viewDocumentationMenuItemIcon');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getWeblibrary_qtip2() {
	 	return MoufManager::getMoufManager()->getInstance('weblibrary.qtip2');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getHtmlMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('htmlMainMenu');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getHtmlFineMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineMainMenu');
	 }

	/**
	 * @return Mouf\Menu\ChooseInstanceMenuItem
	 */
	 public static function getHtmlFineSuppotedLanguageMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineSuppotedLanguageMenuItem');
	 }

	/**
	 * @return Mouf\Menu\ChooseInstanceMenuItem
	 */
	 public static function getHtmlFineEditTranslationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineEditTranslationMenuItem');
	 }

	/**
	 * @return Mouf\Menu\ChooseInstanceMenuItem
	 */
	 public static function getHtmlFineEditionTranslationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineEditionTranslationMenuItem');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Controllers\EditLabelController
	 */
	 public static function getEditLabels() {
	 	return MoufManager::getMoufManager()->getInstance('editLabels');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getMvcMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('mvcMainMenu');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getMvcSplashSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('mvcSplashSubMenu');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getMvcSplashAdminUrlsListMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('mvcSplashAdminUrlsListMenuItem');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\Admin\SplashViewUrlsController
	 */
	 public static function getSplashViewUrls() {
	 	return MoufManager::getMoufManager()->getInstance('splashViewUrls');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getUtilsMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('utilsMainMenu');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getUtilsCacheInterfaceMenu() {
	 	return MoufManager::getMoufManager()->getInstance('utilsCacheInterfaceMenu');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getUtilsCacheInterfacePurgeAllCachesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('utilsCacheInterfacePurgeAllCachesMenuItem');
	 }

	/**
	 * @return Mouf\Menu\ChooseInstanceMenuItem
	 */
	 public static function getUtilsCacheInterfacePurgeOneCacheMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('utilsCacheInterfacePurgeOneCacheMenuItem');
	 }

	/**
	 * @return Mouf\Utils\Cache\Admin\Controllers\PurgeCacheController
	 */
	 public static function getPurgeCaches() {
	 	return MoufManager::getMoufManager()->getInstance('purgeCaches');
	 }

	/**
	 * @return Mouf\Mvc\Splash\SplashGenerateService
	 */
	 public static function getSplashGenerateService() {
	 	return MoufManager::getMoufManager()->getInstance('splashGenerateService');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\Admin\SplashAdminApacheConfigureController
	 */
	 public static function getSplashApacheConfig() {
	 	return MoufManager::getMoufManager()->getInstance('splashApacheConfig');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\Admin\SplashInstallController
	 */
	 public static function getSplashinstall() {
	 	return MoufManager::getMoufManager()->getInstance('splashinstall');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\Admin\SplashPurgeCacheController
	 */
	 public static function getSplashpurgecache() {
	 	return MoufManager::getMoufManager()->getInstance('splashpurgecache');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getMvcSplashPurgeCacheItem() {
	 	return MoufManager::getMoufManager()->getInstance('mvcSplashPurgeCacheItem');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getMvcSplashAdminApacheConfig2Item() {
	 	return MoufManager::getMoufManager()->getInstance('mvcSplashAdminApacheConfig2Item');
	 }

}
?>
