<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'ACT_AS_REPOSITORY' => 
  array (
    'defaultValue' => false,
    'type' => 'bool',
    'comment' => 'If you set this variable to true, your Mouf installation will act as a repository: it will allow other Mouf installations to download any package available.
By default, this is behaviour is disabled.',
  ),
  'UPLOAD_REPOSITORY' => 
  array (
    'defaultValue' => false,
    'type' => 'bool',
    'comment' => 'If true, the repository will accept package upload. When a package is requested for download, it will send the uploaded version (it will not ZIP the package each time), so this setting should be set to FALSE on a developer machine, and only to TRUE on a repository.',
  ),
));

$moufManager->setAllVariables(array (
));

$moufManager->addComponentInstances(array (
  'ajaxinstance' => 
  array (
    'class' => '\\Mouf\\Controllers\\MoufAjaxInstanceController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'components' => 
  array (
    'class' => '\\Mouf\\Controllers\\ComponentsController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'componentsSubMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'viewDeclaredInstancesMenuItem',
        1 => 'createNewInstanceMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Components',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '30',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'config' => 
  array (
    'class' => '\\Mouf\\Controllers\\ConfigController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'configCompleteValidator' => 
  array (
    'class' => 'Mouf\\Validator\\MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Configuration file validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/config_complete_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'createNewInstanceMenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Create a new instance',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/mouf/newInstance',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'createNewInstanceMenuItemIcon',
      ),
    ),
  ),
  'createNewInstanceMenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/page_add.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManager',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'javascript.underscore',
        1 => 'jQueryLibrary',
        2 => 'jQueryUiLibrary',
        3 => 'javascript.jquery-filetree',
        4 => 'javascript.chooseInstancePopupJs',
        5 => 'javascript.syntaxHighlighter',
      ),
    ),
  ),
  'defaultWebLibraryRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\DefaultWebLibraryRenderer',
    'external' => false,
  ),
  'displayGraph' => 
  array (
    'class' => '\\Mouf\\Controllers\\MoufDisplayGraphController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'displayPhpInfoMenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Display PHP Info',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/phpInfo',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'displayPhpInfoMenuItemIcon',
      ),
    ),
  ),
  'displayPhpInfoMenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/table.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'doc' => 
  array (
    'class' => '\\Mouf\\Controllers\\DocumentationController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'documentationMenu' => 'documentationMenu',
    ),
  ),
  'documentationMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
  ),
  'documentationMenuRenderer' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\Menus\\BasicMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'documentationMenu',
    ),
  ),
  'documentationSubMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'viewDocumentationMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Documentation',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '90',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'downloadPackageAction' => 
  array (
    'class' => 'Mouf\\Actions\\DownloadPackageAction',
    'external' => false,
    'fieldBinds' => 
    array (
      'packageDownloadService' => 'packageDownloadService',
    ),
  ),
  'downloadPackages2MenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Download packages',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/packagetransfer/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'downloadPackages2MenuItemIcon',
      ),
    ),
  ),
  'downloadPackages2MenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/download.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'editConfigurationMenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Edit configuration',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/config/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'editConfigurationMenuItemIcon',
      ),
    ),
  ),
  'editConfigurationMenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/note_edit.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'enablePackageAction' => 
  array (
    'class' => 'Mouf\\Actions\\EnablePackageAction',
    'external' => false,
  ),
  'errorLogger' => 
  array (
    'class' => '\\Mouf\\Utils\\Log\\ErrorLogLogger',
    'external' => false,
    'fieldProperties' => 
    array (
      'level' => 
      array (
        'value' => '4',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'includePhpFilesMenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Include PHP files',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/components/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'includePhpFilesMenuItemIcon',
      ),
    ),
  ),
  'includePhpFilesMenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/page_white_php.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'install' => 
  array (
    'class' => '\\Mouf\\Actions\\InstallController',
    'external' => false,
    'fieldBinds' => 
    array (
      'multiStepActionService' => 'installService',
      'template' => 'moufInstallTemplate',
    ),
  ),
  'installProcessValidator' => 
  array (
    'class' => 'Mouf\\Validator\\MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Installation process validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/install_process_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'installService' => 
  array (
    'class' => 'Mouf\\Actions\\MultiStepActionService',
    'external' => false,
    'fieldProperties' => 
    array (
      'actionsStoreFile' => 
      array (
        'value' => 'moufRunningActions.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'installTemplate' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\MoufTemplate\\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        0 => 'defaultWebLibraryManager',
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'instance' => 
  array (
    'class' => '\\Mouf\\Controllers\\MoufInstanceController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'instanceMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
  ),
  'instanceMenuRenderer' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\Menus\\BasicMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'instanceMenu',
    ),
  ),
  'jQueryLibrary' => 
  array (
    'class' => '\\Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery/jquery-1.7.2.min.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'jQueryUiLibrary' => 
  array (
    'class' => '\\Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-ui/js/jquery-ui-1.8.20.custom.min.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-ui/css/ui-darkness/jquery-ui-1.8.20.custom.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
  'javascript.chooseInstancePopupJs' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'views/chooseInstancePopup.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.jquery-filetree' => 
  array (
    'class' => '\\Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-filetree/jqueryFileTree.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery-filetree/jqueryFileTree.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
      'setDependencies' => 
      array (
        0 => 'jQueryLibrary',
      ),
    ),
  ),
  'javascript.syntaxHighlighter' => 
  array (
    'class' => '\\Mouf\\Javascript\\SyntaxHighlighterWebLibrary',
    'external' => false,
    'weak' => false,
  ),
  'javascript.underscore' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'plugins/javascript/underscore/1.3.3/lib/underscore-min.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.underscore.debug' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'plugins/javascript/underscore/1.3.3/lib/underscore.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'login' => 
  array (
    'class' => '\\Mouf\\Controllers\\MoufLoginController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufLoginTemplate',
      'userService' => 'userService',
      'contentBeforeLoginBox' => 
      array (
        0 => 'loginWelcomeMessage',
      ),
    ),
    'fieldProperties' => 
    array (
      'defaultRedirectUrl' => 
      array (
        'value' => 'mouf/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoutRedirectUrl' => 
      array (
        'value' => 'mouf/login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'loginLabel' => 
      array (
        'value' => 'Login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nLoginLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'passwordLabel' => 
      array (
        'value' => 'Password',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nPasswordLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'loginSubmitLabel' => 
      array (
        'value' => 'Login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nLoginSubmitLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'badCredentialsLabel' => 
      array (
        'value' => 'Invalid login or password, please try again.',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nBadCredentialsLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'loginWelcomeMessage' => 
  array (
    'class' => 'Mouf\Html\HtmlElement\HtmlString',
    'external' => false,
    'fieldProperties' => 
    array (
      'Mouf\Html\HtmlElement\HtmlString' => 
      array (
        'value' => '<h1>Login</h1>
<p>Welcome to Mouf. Please login to access the administration interface of your web application.</p>
<br/>
<br/>
<br/>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'logout2MenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Logout',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/login/logout',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'logout2MenuItemIcon',
      ),
    ),
  ),
  'logout2MenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/door_open.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'mainMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'moufSubMenu',
      ),
    ),
  ),
  'manageLocalPackagesMenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Enable/disable local packages',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/packages/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'manageLocalPackagesMenuItemIcon',
      ),
    ),
  ),
  'manageLocalPackagesMenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/folder_add.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'manageRepositoriesMenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Manage repositories',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/repositories/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'manageRepositoriesMenuItemIcon',
      ),
    ),
  ),
  'manageRepositoriesMenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/database.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'miscellaneousSubMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'moufStatus2MenuItem',
        1 => 'displayPhpInfoMenuItem',
        2 => 'logout2MenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Miscellaneous',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '100',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'mouf' => 
  array (
    'class' => '\\Mouf\\Controllers\\MoufController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'moufInstallTemplate' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\MoufTemplate\\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufInstallTemplate2' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\MoufTemplate\\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufLoginTemplate' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\MoufTemplate\\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        0 => 'defaultWebLibraryManager',
      ),
    ),
    'weak' => false,
    'fieldProperties' => 
    array (
      'favIconUrl' => 
      array (
        'value' => 'plugins/html/template/MoufTemplate/1.0/images/favicon.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufStatus2MenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Mouf Status',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/validate/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'moufStatus2MenuItemIcon',
      ),
    ),
  ),
  'moufStatus2MenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/tick.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufSubMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'packagesSubMenu',
        1 => 'phpProjectSubMenu',
        2 => 'componentsSubMenu',
        3 => 'miscellaneousSubMenu',
        4 => 'documentationSubMenu',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Menu',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '0',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufTemplate' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\MoufTemplate\\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        0 => 'defaultWebLibraryManager',
        9 => 'setRootUrlJsBlock',
      ),
      'left' => 
      array (
        0 => 'searchBox',
        1 => 'specialActionsMenuRenderer',
        2 => 'instanceMenuRenderer',
        3 => 'documentationMenuRenderer',
      ),
      'header' => 
      array (
        0 => 'topRibbonMenuRenderer',
      ),
    ),
    'weak' => false,
    'fieldProperties' => 
    array (
      'favIconUrl' => 
      array (
        'value' => 'plugins/html/template/MoufTemplate/1.0/images/favicon.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageDependenciesValidator' => 
  array (
    'class' => 'Mouf\\Validator\\MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Package dependencies validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/package_dependencies_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageDownloadService' => 
  array (
    'class' => 'Mouf\MoufPackageDownloadService',
    'external' => false,
    'fieldBinds' => 
    array (
      'cacheService' => 'repositoryCache',
    ),
  ),
  'packages' => 
  array (
    'class' => '\\Mouf\\Controllers\\PackageController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'multiStepActionService' => 'installService',
    ),
  ),
  'packagesService' => 
  array (
    'class' => '\\Mouf\\Controllers\\PackageServiceController',
    'external' => false,
  ),
  'packagesSubMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'manageLocalPackagesMenuItem',
        1 => 'downloadPackages2MenuItem',
        2 => 'manageRepositoriesMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Packages',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '10',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagetransfer' => 
  array (
    'class' => '\\Mouf\\Controllers\\PackageDownloadController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'packageDownloadService' => 'packageDownloadService',
    ),
  ),
  'phpInfo' => 
  array (
    'class' => '\\Mouf\\Controllers\\PhpInfoController',
    'external' => false,
  ),
  'phpProjectSubMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'editConfigurationMenuItem',
        1 => 'includePhpFilesMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'PHP Project',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '20',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  /*'prototype' => 
  array (
    'class' => 'HtmlJSPrototype',
    'external' => false,
  ),*/
  'redirectAction' => 
  array (
    'class' => 'Mouf\\Actions\\RedirectAction',
    'external' => false,
  ),
  'repositories' => 
  array (
    'class' => '\\Mouf\\Controllers\\RepositorySourceController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'repositoryCache' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
    ),
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => '3600',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'cacheDirectory' => 
      array (
        'value' => 'moufRepositoriesCache/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'relativeToSystemTempDirectory' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'requiredFilesValidator' => 
  array (
    'class' => 'Mouf\\Validator\\MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Required files validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/required_files_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootController' => 
  array (
    'class' => '\\Mouf\\Controllers\\MoufRootController',
    'external' => false,
  ),
  'search' => 
  array (
    'class' => '\\Mouf\\Controllers\\SearchController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'searchService' => 'searchService',
    ),
  ),
  'searchBox' => 
  array (
    'class' => '\\Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'fieldProperties' => 
    array (
      'fileName' => 
      array (
        'value' => 'mouf/views/search/searchbox.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'relativeToRootPath' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'searchService' => 
  array (
    'class' => 'Mouf\\MoufSearchService',
    'external' => false,
    'fieldBinds' => 
    array (
      'searchableServices' => 
      array (
        0 => 'mouf',
      ),
    ),
  ),
  'setRootUrlJsBlock' => 
  array (
    'class' => '\\Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fileName' => 
      array (
        'value' => 'mouf/views/instances/setRootUrlBlock.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'relativeToRootPath' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'specialActionsMenu' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
  ),
  'specialActionsMenuRenderer' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\Menus\\BasicMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'specialActionsMenu',
    ),
  ),
  'splash' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Splash',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
      'defaultTemplate' => 'moufTemplate',
    ),
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'supportsHttps' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
  ),
  'splashTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'plugins/mvc/splash-common/3.2/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'splashBrowserLanguageDetection',
    ),
  ),
  'topRibbonMenuRenderer' => 
  array (
    'class' => '\\Mouf\\Html\\Template\\Menus\\TopRibbonMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'mainMenu',
    ),
  ),
/*  'topSliderMenuRenderer' => 
  array (
    'class' => 'TopSliderMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'mainMenu',
    ),
  ),*/
  'userFileDao' => 
  array (
    'class' => 'Mouf\\Security\\UserFileDao\\UserFileDao',
    'external' => false,
    'fieldProperties' => 
    array (
      'userFile' => 
      array (
        'value' => 'MoufUsers.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userService' => 
  array (
    'class' => 'Mouf\\Security\\UserService\\UserService',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
      'userDao' => 'userFileDao',
    ),
    'fieldProperties' => 
    array (
      'loginPageUrl' => 
      array (
        'value' => 'mouf/login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'sessionPrefix' => 
      array (
        'value' => 'Mouf',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'redirectParameter' => 
      array (
        'value' => 'redirect',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validate' => 
  array (
    'class' => '\\Mouf\\Controllers\\MoufValidatorController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'validatorService' => 'validatorService',
    ),
  ),
  'validatorService' => 
  array (
    'class' => '\\Mouf\\Validator\\MoufValidatorService',
    'external' => false,
    'fieldBinds' => 
    array (
      'validators' => 
      array (
        0 => 'requiredFilesValidator',
        1 => 'configCompleteValidator',
        2 => 'installProcessValidator',
        3 => 'packageDependenciesValidator',
      ),
    ),
  ),
  'viewDeclaredInstancesMenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'View declared instances',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/mouf/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'viewDeclaredInstancesMenuItemIcon',
      ),
    ),
  ),
  'viewDeclaredInstancesMenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/page_white_stack.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'viewDocumentationMenuItem' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'View packages documentation',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/doc/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'viewDocumentationMenuItemIcon',
      ),
    ),
  ),
  'viewDocumentationMenuItemIcon' => 
  array (
    'class' => '\\Mouf\\Html\\Widgets\\Menu\\MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/report.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
));

$moufManager->registerComponent('validator/MoufValidatorService.php', 'auto');
$moufManager->registerComponent('validator/MoufBasicValidationProvider.php', 'auto');
$moufManager->registerComponent('controllers/DisplayPackageListInterface.php', 'auto');
$moufManager->registerComponent('MoufSearchable.php', 'auto');
$moufManager->registerComponent('MoufSearchService.php', 'auto');
$moufManager->registerComponent('actions/MoufActionDescriptor.php', 'auto');
$moufManager->registerComponent('actions/MoufActionProvider.php', 'auto');
$moufManager->registerComponent('actions/DownloadPackageAction.php', 'auto');
$moufManager->registerComponent('actions/EnablePackageAction.php', 'auto');
$moufManager->registerComponent('actions/RedirectAction.php', 'auto');
$moufManager->registerComponent('actions/MultiStepActionService.php', 'auto');
$moufManager->registerComponent('actions/InstallController.php', 'auto');
$moufManager->registerComponent('actions/MoufActionResultInterface.php', 'auto');
$moufManager->registerComponent('actions/MoufActionRedirectResult.php', 'auto');
$moufManager->registerComponent('actions/MoufActionDoneResult.php', 'auto');
$moufManager->registerComponent('controllers/MoufController.php', 'auto');
$moufManager->registerComponent('controllers/MoufRootController.php', 'auto');
$moufManager->registerComponent('controllers/ComponentsController.php', 'auto');
$moufManager->registerComponent('controllers/PackageController.php', 'auto');
$moufManager->registerComponent('controllers/MoufInstanceController.php', 'auto');
$moufManager->registerComponent('controllers/MoufAjaxInstanceController.php', 'auto');
$moufManager->registerComponent('controllers/MoufDisplayGraphController.php', 'auto');
$moufManager->registerComponent('controllers/ConfigController.php', 'auto');
$moufManager->registerComponent('controllers/MoufValidatorController.php', 'auto');
$moufManager->registerComponent('controllers/MoufLoginController.php', 'auto');
$moufManager->registerComponent('controllers/PackageServiceController.php', 'auto');
$moufManager->registerComponent('controllers/RepositorySourceController.php', 'auto');
$moufManager->registerComponent('controllers/PackageDownloadController.php', 'auto');
$moufManager->registerComponent('controllers/DocumentationController.php', 'auto');
$moufManager->registerComponent('MoufPackageDownloadService.php', 'auto');
$moufManager->registerComponent('MoufNetworkException.php', 'auto');
$moufManager->registerComponent('MoufRepository.php', 'auto');
$moufManager->registerComponent('MoufUtils.php', 'auto');
$moufManager->registerComponent('controllers/PhpInfoController.php', 'auto');
$moufManager->registerComponent('controllers/SearchController.php', 'auto');
$moufManager->registerComponent('actions/InstallUtils.php', 'auto');
$moufManager->registerComponent('load.php', 'auto');

unset($moufManager);

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class Mouf {
	/**
	 * @return MoufAjaxInstanceController
	 */
	 public static function getAjaxinstance() {
	 	return MoufManager::getMoufManager()->getInstance('ajaxinstance');
	 }

	/**
	 * @return ComponentsController
	 */
	 public static function getComponents() {
	 	return MoufManager::getMoufManager()->getInstance('components');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getComponentsSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('componentsSubMenu');
	 }

	/**
	 * @return ConfigController
	 */
	 public static function getConfig() {
	 	return MoufManager::getMoufManager()->getInstance('config');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getConfigCompleteValidator() {
	 	return MoufManager::getMoufManager()->getInstance('configCompleteValidator');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getCreateNewInstanceMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('createNewInstanceMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getCreateNewInstanceMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('createNewInstanceMenuItemIcon');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryManager');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\DefaultWebLibraryRenderer
	 */
	 public static function getDefaultWebLibraryRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryRenderer');
	 }

	/**
	 * @return MoufDisplayGraphController
	 */
	 public static function getDisplayGraph() {
	 	return MoufManager::getMoufManager()->getInstance('displayGraph');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getDisplayPhpInfoMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('displayPhpInfoMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getDisplayPhpInfoMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('displayPhpInfoMenuItemIcon');
	 }

	/**
	 * @return DocumentationController
	 */
	 public static function getDoc() {
	 	return MoufManager::getMoufManager()->getInstance('doc');
	 }

	/**
	 * @return Menu
	 */
	 public static function getDocumentationMenu() {
	 	return MoufManager::getMoufManager()->getInstance('documentationMenu');
	 }

	/**
	 * @return \\Mouf\\Html\\Template\\Menus\\BasicMenuRenderer
	 */
	 public static function getDocumentationMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('documentationMenuRenderer');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getDocumentationSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('documentationSubMenu');
	 }

	/**
	 * @return DownloadPackageAction
	 */
	 public static function getDownloadPackageAction() {
	 	return MoufManager::getMoufManager()->getInstance('downloadPackageAction');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getDownloadPackages2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('downloadPackages2MenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getDownloadPackages2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('downloadPackages2MenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getEditConfigurationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('editConfigurationMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getEditConfigurationMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('editConfigurationMenuItemIcon');
	 }

	/**
	 * @return EnablePackageAction
	 */
	 public static function getEnablePackageAction() {
	 	return MoufManager::getMoufManager()->getInstance('enablePackageAction');
	 }

	/**
	 * @return \Mouf\Utils\Log\ErrorLogLogger
	 */
	 public static function getErrorLogger() {
	 	return MoufManager::getMoufManager()->getInstance('errorLogger');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getIncludePhpFilesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('includePhpFilesMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getIncludePhpFilesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('includePhpFilesMenuItemIcon');
	 }

	/**
	 * @return InstallController
	 */
	 public static function getInstall() {
	 	return MoufManager::getMoufManager()->getInstance('install');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getInstallProcessValidator() {
	 	return MoufManager::getMoufManager()->getInstance('installProcessValidator');
	 }

	/**
	 * @return MultiStepActionService
	 */
	 public static function getInstallService() {
	 	return MoufManager::getMoufManager()->getInstance('installService');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public static function getInstallTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('installTemplate');
	 }

	/**
	 * @return MoufInstanceController
	 */
	 public static function getInstance() {
	 	return MoufManager::getMoufManager()->getInstance('instance');
	 }

	/**
	 * @return Menu
	 */
	 public static function getInstanceMenu() {
	 	return MoufManager::getMoufManager()->getInstance('instanceMenu');
	 }

	/**
	 * @return \\Mouf\\Html\\Template\\Menus\\BasicMenuRenderer
	 */
	 public static function getInstanceMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('instanceMenuRenderer');
	 }

	/**
	 * @return HtmlJSJQuery
	 */
	 public static function getJQuery() {
	 	return MoufManager::getMoufManager()->getInstance('jQuery');
	 }

	/**
	 * @return \Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryLibrary');
	 }

	/**
	 * @return \Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryUiLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryUiLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_chooseInstancePopupJs() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.chooseInstancePopupJs');
	 }

	/**
	 * @return \Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_jqueryfiletree() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.jquery-filetree');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_underscore() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.underscore');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_underscore_debug() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.underscore.debug');
	 }

	/**
	 * @return MoufLoginController
	 */
	 public static function getLogin() {
	 	return MoufManager::getMoufManager()->getInstance('login');
	 }

	/**
	 * @return HtmlString
	 */
	 public static function getLoginWelcomeMessage() {
	 	return MoufManager::getMoufManager()->getInstance('loginWelcomeMessage');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getLogout2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('logout2MenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getLogout2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('logout2MenuItemIcon');
	 }

	/**
	 * @return Menu
	 */
	 public static function getMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('mainMenu');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getManageLocalPackagesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('manageLocalPackagesMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getManageLocalPackagesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('manageLocalPackagesMenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getManageRepositoriesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('manageRepositoriesMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getManageRepositoriesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('manageRepositoriesMenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMiscellaneousSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('miscellaneousSubMenu');
	 }

	/**
	 * @return MoufController
	 */
	 public static function getMouf() {
	 	return MoufManager::getMoufManager()->getInstance('mouf');
	 }

	/**
	 * @return \Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getMoufInstallTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufInstallTemplate');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public static function getMoufInstallTemplate2() {
	 	return MoufManager::getMoufManager()->getInstance('moufInstallTemplate2');
	 }

	/**
	 * @return \Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getMoufLoginTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufLoginTemplate');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMoufStatus2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('moufStatus2MenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getMoufStatus2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('moufStatus2MenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMoufSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('moufSubMenu');
	 }

	/**
	 * @return \Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getMoufTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufTemplate');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getPackageDependenciesValidator() {
	 	return MoufManager::getMoufManager()->getInstance('packageDependenciesValidator');
	 }

	/**
	 * @return MoufPackageDownloadService
	 */
	 public static function getPackageDownloadService() {
	 	return MoufManager::getMoufManager()->getInstance('packageDownloadService');
	 }

	/**
	 * @return PackageController
	 */
	 public static function getPackages() {
	 	return MoufManager::getMoufManager()->getInstance('packages');
	 }

	/**
	 * @return PackageServiceController
	 */
	 public static function getPackagesService() {
	 	return MoufManager::getMoufManager()->getInstance('packagesService');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getPackagesSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('packagesSubMenu');
	 }

	/**
	 * @return PackageDownloadController
	 */
	 public static function getPackagetransfer() {
	 	return MoufManager::getMoufManager()->getInstance('packagetransfer');
	 }

	/**
	 * @return PhpInfoController
	 */
	 public static function getPhpInfo() {
	 	return MoufManager::getMoufManager()->getInstance('phpInfo');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getPhpProjectSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('phpProjectSubMenu');
	 }

	/**
	 * @return HtmlJSPrototype
	 */
	 public static function getPrototype() {
	 	return MoufManager::getMoufManager()->getInstance('prototype');
	 }

	/**
	 * @return RedirectAction
	 */
	 public static function getRedirectAction() {
	 	return MoufManager::getMoufManager()->getInstance('redirectAction');
	 }

	/**
	 * @return RepositorySourceController
	 */
	 public static function getRepositories() {
	 	return MoufManager::getMoufManager()->getInstance('repositories');
	 }

	/**
	 * @return FileCache
	 */
	 public static function getRepositoryCache() {
	 	return MoufManager::getMoufManager()->getInstance('repositoryCache');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getRequiredFilesValidator() {
	 	return MoufManager::getMoufManager()->getInstance('requiredFilesValidator');
	 }

	/**
	 * @return MoufRootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->getInstance('rootController');
	 }

	/**
	 * @return SearchController
	 */
	 public static function getSearch() {
	 	return MoufManager::getMoufManager()->getInstance('search');
	 }

	/**
	 * @return \\Mouf\\Html\\HtmlElement\\HtmlFromFile
	 */
	 public static function getSearchBox() {
	 	return MoufManager::getMoufManager()->getInstance('searchBox');
	 }

	/**
	 * @return MoufSearchService
	 */
	 public static function getSearchService() {
	 	return MoufManager::getMoufManager()->getInstance('searchService');
	 }

	/**
	 * @return \\Mouf\\Html\\HtmlElement\\HtmlFromFile
	 */
	 public static function getSetRootUrlJsBlock() {
	 	return MoufManager::getMoufManager()->getInstance('setRootUrlJsBlock');
	 }

	/**
	 * @return Menu
	 */
	 public static function getSpecialActionsMenu() {
	 	return MoufManager::getMoufManager()->getInstance('specialActionsMenu');
	 }

	/**
	 * @return \\Mouf\\Html\\Template\\Menus\\BasicMenuRenderer
	 */
	 public static function getSpecialActionsMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('specialActionsMenuRenderer');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Splash
	 */
	 public static function getSplash() {
	 	return MoufManager::getMoufManager()->getInstance('splash');
	 }

	/**
	 * @return BrowserLanguageDetection
	 */
	 public static function getSplashBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->getInstance('splashBrowserLanguageDetection');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public static function getSplashTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('splashTemplate');
	 }

	/**
	 * @return FinePHPArrayTranslationService
	 */
	 public static function getSplashTranslateService() {
	 	return MoufManager::getMoufManager()->getInstance('splashTranslateService');
	 }

	/**
	 * @return HtmlJSSyntaxHighlighter
	 */
	 public static function getSyntaxHighlighter() {
	 	return MoufManager::getMoufManager()->getInstance('syntaxHighlighter');
	 }

	/**
	 * @return TopRibbonMenuRenderer
	 */
	 public static function getTopRibbonMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('topRibbonMenuRenderer');
	 }

	/**
	 * @return TopSliderMenuRenderer
	 */
	 public static function getTopSliderMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('topSliderMenuRenderer');
	 }

	/**
	 * @return UserFileDao
	 */
	 public static function getUserFileDao() {
	 	return MoufManager::getMoufManager()->getInstance('userFileDao');
	 }

	/**
	 * @return MoufUserService
	 */
	 public static function getUserService() {
	 	return MoufManager::getMoufManager()->getInstance('userService');
	 }

	/**
	 * @return MoufValidatorController
	 */
	 public static function getValidate() {
	 	return MoufManager::getMoufManager()->getInstance('validate');
	 }

	/**
	 * @return MoufValidatorService
	 */
	 public static function getValidatorService() {
	 	return MoufManager::getMoufManager()->getInstance('validatorService');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getViewDeclaredInstancesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('viewDeclaredInstancesMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getViewDeclaredInstancesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('viewDeclaredInstancesMenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getViewDocumentationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('viewDocumentationMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getViewDocumentationMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('viewDocumentationMenuItemIcon');
	 }

	/**
	 * @return \Mouf\Javascript\SyntaxHighlighterWebLibrary
	 */
	 public static function getJavascript_syntaxHighlighter() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.syntaxHighlighter');
	 }

}
?>
