<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;

MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'ACT_AS_REPOSITORY' => 
  array (
    'defaultValue' => false,
    'type' => 'bool',
    'comment' => 'If you set this variable to true, your Mouf installation will act as a repository: it will allow other Mouf installations to download any package available.
By default, this is behaviour is disabled.',
  ),
  'UPLOAD_REPOSITORY' => 
  array (
    'defaultValue' => false,
    'type' => 'bool',
    'comment' => 'If true, the repository will accept package upload. When a package is requested for download, it will send the uploaded version (it will not ZIP the package each time), so this setting should be set to FALSE on a developer machine, and only to TRUE on a repository.',
  ),
));

$moufManager->setPackagesByXmlFile(array (
  0 => 'utils/common/getvars/1.1/package.xml',
  1 => 'utils/log/log_interface/1.1/package.xml',
  2 => 'utils/common/conditioninterface/1.0/package.xml',
  3 => 'html/htmlelement/1.0/package.xml',
  4 => 'utils/export/phpexcel/1.7.5/package.xml',
  5 => 'utils/icons/famfamfam/1.3/package.xml',
  6 => 'html/template/BaseTemplate/1.0/package.xml',
  7 => 'javascript/jquery/jquery/1.6/package.xml',
  8 => 'javascript/jquery/jquery-fixedheadertable/1.3/package.xml',
  9 => 'utils/i18n/fine/2.1/package.xml',
  10 => 'html/widgets/menu/1.0/package.xml',
  11 => 'html/template/SplashTemplate/2.0/package.xml',
  12 => 'javascript/jquery/jquery-autogrow/1.2.2/package.xml',
  13 => 'javascript/jquery/jquery-ui/1.8.20/package.xml',
  14 => 'javascript/jquery/jqueryFileTree/1.01/package.xml',
  15 => 'javascript/jit/1.1.2/package.xml',
  16 => 'javascript/prototype/1.6.0.1/package.xml',
  17 => 'utils/log/errorlog_logger/1.1/package.xml',
  18 => 'security/userservice/1.0/package.xml',
  19 => 'security/userfiledao/1.0/package.xml',
  20 => 'utils/cache/cache-interface/1.0/package.xml',
  21 => 'utils/cache/file-cache/1.1/package.xml',
  22 => 'html/template/menus/topslidermenu/1.0/package.xml',
  23 => 'utils/common/validators/1.0/package.xml',
  24 => 'mvc/splash-common/3.2/package.xml',
  25 => 'mvc/splash/3.2/package.xml',
  26 => 'security/simplelogincontroller/1.0/package.xml',
  27 => 'security/userservice-splash/3.0/package.xml',
  28 => 'html/widgets/scripttagwidget/1.0/package.xml',
  29 => 'html/template/MoufTemplate/1.0/package.xml',
  30 => 'html/template/menus/topribbonmenu/1.0/package.xml',
  31 => 'javascript/syntaxhighlighter/3.0.83/package.xml',
  32 => 'html/utils/weblibrarymanager/1.0/package.xml',
  33 => 'javascript/underscore/1.3.3/package.xml',
));

$moufManager->setPackagesByXmlFileInAdminScope(array (
));

/*require dirname(__FILE__).'/../plugins/utils/common/conditioninterface/1.0/ConditionsExternalComponent.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jquery/1.6/JQueryExternalComponent.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jquery-fixedheadertable/1.3/JQueryFixedHeaderTableExternalComponent.php';
require dirname(__FILE__).'/../plugins/utils/i18n/fine/2.1/FineExternalComponents.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jquery-autogrow/1.2.2/JQueryAutoGrowExternalComponent.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jquery-ui/1.8.20/JQueryUIExternalComponent.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jqueryFileTree/1.01/JQueryFileTreeExternalComponent.php';
require dirname(__FILE__).'/../plugins/html/template/menus/topslidermenu/1.0/TopSliderExternalComponent.php';
require dirname(__FILE__).'/../plugins/utils/common/validators/1.0/ValidatorsExternalComponents.php';
require dirname(__FILE__).'/../plugins/mvc/splash/3.2/SplashExternalComponent.php';
require dirname(__FILE__).'/../plugins/html/template/menus/topribbonmenu/1.0/TopRibbonExternalComponent.php';
*/

$moufManager->setAllVariables(array (
));

$moufManager->addComponentInstances(array (
  'ajaxinstance' => 
  array (
    'class' => 'MoufAjaxInstanceController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'chooseInstancePopupJs' => 
  array (
    'class' => 'ScriptTagWidget',
    'external' => false,
    'fieldProperties' => 
    array (
      'cssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'jsFiles' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/chooseInstancePopup.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'components' => 
  array (
    'class' => 'ComponentsController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'componentsSubMenu' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'viewDeclaredInstancesMenuItem',
        1 => 'createNewInstanceMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Components',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '30',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'config' => 
  array (
    'class' => 'ConfigController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'configCompleteValidator' => 
  array (
    'class' => 'MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Configuration file validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/config_complete_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'createNewInstanceMenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Create a new instance',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/mouf/newInstance',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'createNewInstanceMenuItemIcon',
      ),
    ),
  ),
  'createNewInstanceMenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/page_add.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\Html\Utils\WebLibraryManager\WebLibraryManager',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'javascript.underscore',
      ),
    ),
  ),
  'defaultWebLibraryRenderer' => 
  array (
    'class' => 'DefaultWebLibraryRenderer',
    'external' => false,
  ),
  'displayGraph' => 
  array (
    'class' => 'MoufDisplayGraphController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'displayPhpInfoMenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Display PHP Info',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/phpInfo',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'displayPhpInfoMenuItemIcon',
      ),
    ),
  ),
  'displayPhpInfoMenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/table.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'doc' => 
  array (
    'class' => 'DocumentationController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'documentationMenu' => 'documentationMenu',
    ),
  ),
  'documentationMenu' => 
  array (
    'class' => 'Menu',
    'external' => false,
  ),
  'documentationMenuRenderer' => 
  array (
    'class' => 'SplashMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'documentationMenu',
    ),
  ),
  'documentationSubMenu' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'viewDocumentationMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Documentation',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '90',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'downloadPackageAction' => 
  array (
    'class' => 'DownloadPackageAction',
    'external' => false,
    'fieldBinds' => 
    array (
      'packageDownloadService' => 'packageDownloadService',
    ),
  ),
  'downloadPackages2MenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Download packages',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/packagetransfer/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'downloadPackages2MenuItemIcon',
      ),
    ),
  ),
  'downloadPackages2MenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/download.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'editConfigurationMenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Edit configuration',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/config/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'editConfigurationMenuItemIcon',
      ),
    ),
  ),
  'editConfigurationMenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/note_edit.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'enablePackageAction' => 
  array (
    'class' => 'EnablePackageAction',
    'external' => false,
  ),
  'errorLogger' => 
  array (
    'class' => '\Mouf\Utils\Log\ErrorLogLogger',
    'external' => false,
    'fieldProperties' => 
    array (
      'level' => 
      array (
        'value' => '4',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'includePhpFilesMenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Include PHP files',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/components/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'includePhpFilesMenuItemIcon',
      ),
    ),
  ),
  'includePhpFilesMenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/page_white_php.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'install' => 
  array (
    'class' => 'InstallController',
    'external' => false,
    'fieldBinds' => 
    array (
      'multiStepActionService' => 'installService',
      'template' => 'moufInstallTemplate',
    ),
  ),
  'installProcessValidator' => 
  array (
    'class' => 'MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Installation process validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/install_process_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'installService' => 
  array (
    'class' => 'MultiStepActionService',
    'external' => false,
    'fieldProperties' => 
    array (
      'actionsStoreFile' => 
      array (
        'value' => 'moufRunningActions.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'installTemplate' => 
  array (
    'class' => 'SplashTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
      	0 => 'defaultWebLibraryManager',
        2 => 'jqueryFileTree',
        3 => 'jquery-autogrow-1.2.2',
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'instance' => 
  array (
    'class' => 'MoufInstanceController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'instanceMenu' => 
  array (
    'class' => 'Menu',
    'external' => false,
  ),
  'instanceMenuRenderer' => 
  array (
    'class' => 'SplashMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'instanceMenu',
    ),
  ),
  'jQuery' => 
  array (
    'class' => 'HtmlJSJQuery',
    'external' => false,
    'fieldProperties' => 
    array (
      'noConflictMode' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.underscore' => 
  array (
    'class' => 'Mouf\Html\Utils\WebLibraryManager\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'plugins/javascript/underscore/1.3.3/lib/underscore-min.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'javascript.underscore.debug' => 
  array (
    'class' => 'Mouf\Html\Utils\WebLibraryManager\WebLibrary',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setJsFiles' => 
      array (
        'value' => 
        array (
          0 => 'plugins/javascript/underscore/1.3.3/lib/underscore.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssFiles' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'jqueryFileTree' => 
  array (
    'class' => 'HtmlJSJQueryFileTree',
    'external' => false,
  ),
  'jqueryui' => 
  array (
    'class' => 'HtmlJSJQueryUI',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'includeDefaultCss' => 
      array (
        'value' => 'ui-lightness',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'login' => 
  array (
    'class' => 'MoufLoginController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufLoginTemplate',
      'userService' => 'userService',
      'contentBeforeLoginBox' => 
      array (
        0 => 'loginWelcomeMessage',
      ),
    ),
    'fieldProperties' => 
    array (
      'defaultRedirectUrl' => 
      array (
        'value' => 'mouf/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoutRedirectUrl' => 
      array (
        'value' => 'mouf/login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'loginLabel' => 
      array (
        'value' => 'Login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nLoginLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'passwordLabel' => 
      array (
        'value' => 'Password',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nPasswordLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'loginSubmitLabel' => 
      array (
        'value' => 'Login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nLoginSubmitLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'badCredentialsLabel' => 
      array (
        'value' => 'Invalid login or password, please try again.',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nBadCredentialsLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'loginWelcomeMessage' => 
  array (
    'class' => 'HtmlString',
    'external' => false,
    'fieldProperties' => 
    array (
      'htmlString' => 
      array (
        'value' => '<h1>Login</h1>
<p>Welcome to Mouf. Please login to access the administration interface of your web application.</p>
<br/>
<br/>
<br/>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'logout2MenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Logout',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/login/logout',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'logout2MenuItemIcon',
      ),
    ),
  ),
  'logout2MenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/door_open.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'mainMenu' => 
  array (
    'class' => 'Menu',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'moufSubMenu',
      ),
    ),
  ),
  'manageLocalPackagesMenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Enable/disable local packages',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/packages/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'manageLocalPackagesMenuItemIcon',
      ),
    ),
  ),
  'manageLocalPackagesMenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/folder_add.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'manageRepositoriesMenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Manage repositories',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/repositories/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'manageRepositoriesMenuItemIcon',
      ),
    ),
  ),
  'manageRepositoriesMenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/database.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'miscellaneousSubMenu' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'moufStatus2MenuItem',
        1 => 'displayPhpInfoMenuItem',
        2 => 'logout2MenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Miscellaneous',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '100',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'mouf' => 
  array (
    'class' => 'MoufController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'moufInstallTemplate' => 
  array (
    'class' => '\Mouf\Html\Template\MoufTemplate\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        0 => 'jQuery',
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufInstallTemplate2' => 
  array (
    'class' => 'SplashTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        0 => 'jQuery',
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufLoginTemplate' => 
  array (
    'class' => '\Mouf\Html\Template\MoufTemplate\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        /*0 => 'prototype',*/
      	0 => 'defaultWebLibraryManager',
      	3 => 'jqueryFileTree',
        4 => 'jquery-autogrow-1.2.2',
      ),
    ),
    'weak' => false,
    'fieldProperties' => 
    array (
      'favIconUrl' => 
      array (
        'value' => 'plugins/html/template/MoufTemplate/1.0/images/favicon.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufStatus2MenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Mouf Status',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/validate/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'moufStatus2MenuItemIcon',
      ),
    ),
  ),
  'moufStatus2MenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/tick.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufSubMenu' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'packagesSubMenu',
        1 => 'phpProjectSubMenu',
        2 => 'componentsSubMenu',
        3 => 'miscellaneousSubMenu',
        4 => 'documentationSubMenu',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Menu',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '0',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufTemplate' => 
  array (
    'class' => '\Mouf\Html\Template\MoufTemplate\MoufTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        /*0 => 'prototype',*/
      	0 => 'defaultWebLibraryManager',
      	3 => 'jqueryFileTree',
        4 => 'jquery-autogrow-1.2.2',
        5 => 'chooseInstancePopupJs',
        6 => 'htmlMenuTopRibbonHead',
        7 => 'syntaxHighlighter',
        9 => 'setRootUrlJsBlock',
      ),
      'left' => 
      array (
        0 => 'searchBox',
        1 => 'specialActionsMenuRenderer',
        2 => 'instanceMenuRenderer',
        3 => 'documentationMenuRenderer',
      ),
      'header' => 
      array (
        0 => 'topRibbonMenuRenderer',
      ),
    ),
    'weak' => false,
    'fieldProperties' => 
    array (
      'favIconUrl' => 
      array (
        'value' => 'plugins/html/template/MoufTemplate/1.0/images/favicon.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageDependenciesValidator' => 
  array (
    'class' => 'MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Package dependencies validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/package_dependencies_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageDownloadService' => 
  array (
    'class' => 'MoufPackageDownloadService',
    'external' => false,
    'fieldBinds' => 
    array (
      'cacheService' => 'repositoryCache',
    ),
  ),
  'packages' => 
  array (
    'class' => 'PackageController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'multiStepActionService' => 'installService',
    ),
  ),
  'packagesService' => 
  array (
    'class' => 'PackageServiceController',
    'external' => false,
  ),
  'packagesSubMenu' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'manageLocalPackagesMenuItem',
        1 => 'downloadPackages2MenuItem',
        2 => 'manageRepositoriesMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'Packages',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '10',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagetransfer' => 
  array (
    'class' => 'PackageDownloadController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'packageDownloadService' => 'packageDownloadService',
    ),
  ),
  'phpInfo' => 
  array (
    'class' => 'PhpInfoController',
    'external' => false,
  ),
  'phpProjectSubMenu' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterBinds' => 
    array (
      'setChildren' => 
      array (
        0 => 'editConfigurationMenuItem',
        1 => 'includePhpFilesMenuItem',
      ),
    ),
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'PHP Project',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '20',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'prototype' => 
  array (
    'class' => 'HtmlJSPrototype',
    'external' => false,
  ),
  'redirectAction' => 
  array (
    'class' => 'RedirectAction',
    'external' => false,
  ),
  'repositories' => 
  array (
    'class' => 'RepositorySourceController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'repositoryCache' => 
  array (
    'class' => 'FileCache',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
    ),
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => '3600',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'cacheDirectory' => 
      array (
        'value' => 'moufRepositoriesCache/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'relativeToSystemTempDirectory' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'requiredFilesValidator' => 
  array (
    'class' => 'MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Required files validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/required_files_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootController' => 
  array (
    'class' => 'MoufRootController',
    'external' => false,
  ),
  'search' => 
  array (
    'class' => 'SearchController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'searchService' => 'searchService',
    ),
  ),
  'searchBox' => 
  array (
    'class' => 'HtmlFromFile',
    'external' => false,
    'fieldProperties' => 
    array (
      'fileName' => 
      array (
        'value' => 'mouf/views/search/searchbox.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'relativeToRootPath' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'searchService' => 
  array (
    'class' => 'MoufSearchService',
    'external' => false,
    'fieldBinds' => 
    array (
      'searchableServices' => 
      array (
        0 => 'mouf',
      ),
    ),
  ),
  'setRootUrlJsBlock' => 
  array (
    'class' => 'HtmlFromFile',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'fileName' => 
      array (
        'value' => 'mouf/views/instances/setRootUrlBlock.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'relativeToRootPath' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'specialActionsMenu' => 
  array (
    'class' => 'Menu',
    'external' => false,
  ),
  'specialActionsMenuRenderer' => 
  array (
    'class' => 'SplashMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'specialActionsMenu',
    ),
  ),
  'splash' => 
  array (
    'class' => 'Mouf\Mvc\Splash\Splash',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
      'defaultTemplate' => 'moufTemplate',
    ),
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'supportsHttps' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashBrowserLanguageDetection' => 
  array (
    'class' => 'BrowserLanguageDetection',
    'external' => false,
  ),
  'splashTemplate' => 
  array (
    'class' => 'SplashTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        /*0 => 'prototype',*/
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashTranslateService' => 
  array (
    'class' => 'FinePHPArrayTranslationService',
    'external' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'plugins/mvc/splash-common/3.2/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'splashBrowserLanguageDetection',
    ),
  ),
  'syntaxHighlighter' => 
  array (
    'class' => 'HtmlJSSyntaxHighlighter',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'brushes' => 
      array (
        'value' => 
        array (
          'applescript' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushAppleScript.js',
          'as3' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushAS3.js',
          'bash' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushBash.js',
          'coldfusion' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushColdFusion.js',
          'cpp' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushCpp.js',
          'csharp' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushCSharp.js',
          'css' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushCss.js',
          'delphi' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushDelphi.js',
          'diff' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrush.js',
          'erlang' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushErlang.js',
          'groovy' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushGroovy.js',
          'java' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushJava.js',
          'javaFX' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrush.js',
          'jscript' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushJScript.js',
          'javascript' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushJScript.js',
          'js' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushJScript.js',
          'perl' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushPerl.js',
          'plain' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushPlain.js',
          'powershell' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushPowerShell.js',
          'python' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushPython.js',
          'ruby' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushRuby.js',
          'sass' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushSass.js',
          'scala' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushScala.js',
          'sql' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushSql.js',
          'vb' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushVb.js',
          'xml' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushXml.js',
          'html' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushXml.js',
          'xhtml' => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushXml.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'staticBrushes' => 
      array (
        'value' => 
        array (
          0 => 'plugins/javascript/syntaxhighlighter/3.0.83/scripts/shBrushPhp.js',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'theme' => 
      array (
        'value' => 'plugins/javascript/syntaxhighlighter/3.0.83/styles/shCoreDefault.css',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'topRibbonMenuRenderer' => 
  array (
    'class' => 'TopRibbonMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'mainMenu',
    ),
  ),
  'topSliderMenuRenderer' => 
  array (
    'class' => 'TopSliderMenuRenderer',
    'external' => false,
    'fieldBinds' => 
    array (
      'menu' => 'mainMenu',
    ),
  ),
  'userFileDao' => 
  array (
    'class' => 'UserFileDao',
    'external' => false,
    'fieldProperties' => 
    array (
      'userFile' => 
      array (
        'value' => 'MoufUsers.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userService' => 
  array (
    'class' => 'MoufUserService',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
      'userDao' => 'userFileDao',
    ),
    'fieldProperties' => 
    array (
      'loginPageUrl' => 
      array (
        'value' => 'mouf/login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'sessionPrefix' => 
      array (
        'value' => 'Mouf',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'redirectParameter' => 
      array (
        'value' => 'redirect',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validate' => 
  array (
    'class' => 'MoufValidatorController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'validatorService' => 'validatorService',
    ),
  ),
  'validatorService' => 
  array (
    'class' => 'MoufValidatorService',
    'external' => false,
    'fieldBinds' => 
    array (
      'validators' => 
      array (
        0 => 'requiredFilesValidator',
        1 => 'configCompleteValidator',
        2 => 'installProcessValidator',
        3 => 'packageDependenciesValidator',
      ),
    ),
  ),
  'viewDeclaredInstancesMenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'View declared instances',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/mouf/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'viewDeclaredInstancesMenuItemIcon',
      ),
    ),
  ),
  'viewDeclaredInstancesMenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/page_white_stack.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'viewDocumentationMenuItem' => 
  array (
    'class' => 'MenuItem',
    'external' => false,
    'setterProperties' => 
    array (
      'setLabel' => 
      array (
        'value' => 'View packages documentation',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setUrl' => 
      array (
        'value' => 'mouf/doc/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsActive' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setIsExtended' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPriority' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setPropagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'setActivateBasedOnUrl' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setAdditionalStyles' => 
      array (
        0 => 'viewDocumentationMenuItemIcon',
      ),
    ),
  ),
  'viewDocumentationMenuItemIcon' => 
  array (
    'class' => 'MenuItemStyleIcon',
    'external' => false,
    'setterProperties' => 
    array (
      'setUrl' => 
      array (
        'value' => 'mouf/views/images/report.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
));

$moufManager->registerComponent('validator/MoufValidatorService.php', 'auto');
$moufManager->registerComponent('validator/MoufBasicValidationProvider.php', 'auto');
$moufManager->registerComponent('controllers/DisplayPackageListInterface.php', 'auto');
$moufManager->registerComponent('MoufSearchable.php', 'auto');
$moufManager->registerComponent('MoufSearchService.php', 'auto');
$moufManager->registerComponent('actions/MoufActionDescriptor.php', 'auto');
$moufManager->registerComponent('actions/MoufActionProvider.php', 'auto');
$moufManager->registerComponent('actions/DownloadPackageAction.php', 'auto');
$moufManager->registerComponent('actions/EnablePackageAction.php', 'auto');
$moufManager->registerComponent('actions/RedirectAction.php', 'auto');
$moufManager->registerComponent('actions/MultiStepActionService.php', 'auto');
$moufManager->registerComponent('actions/InstallController.php', 'auto');
$moufManager->registerComponent('actions/MoufActionResultInterface.php', 'auto');
$moufManager->registerComponent('actions/MoufActionRedirectResult.php', 'auto');
$moufManager->registerComponent('actions/MoufActionDoneResult.php', 'auto');
$moufManager->registerComponent('controllers/MoufController.php', 'auto');
$moufManager->registerComponent('controllers/MoufRootController.php', 'auto');
$moufManager->registerComponent('controllers/ComponentsController.php', 'auto');
$moufManager->registerComponent('controllers/PackageController.php', 'auto');
$moufManager->registerComponent('controllers/MoufInstanceController.php', 'auto');
$moufManager->registerComponent('controllers/MoufAjaxInstanceController.php', 'auto');
$moufManager->registerComponent('controllers/MoufDisplayGraphController.php', 'auto');
$moufManager->registerComponent('controllers/ConfigController.php', 'auto');
$moufManager->registerComponent('controllers/MoufValidatorController.php', 'auto');
$moufManager->registerComponent('controllers/MoufLoginController.php', 'auto');
$moufManager->registerComponent('controllers/PackageServiceController.php', 'auto');
$moufManager->registerComponent('controllers/RepositorySourceController.php', 'auto');
$moufManager->registerComponent('controllers/PackageDownloadController.php', 'auto');
$moufManager->registerComponent('controllers/DocumentationController.php', 'auto');
$moufManager->registerComponent('MoufPackageDownloadService.php', 'auto');
$moufManager->registerComponent('MoufNetworkException.php', 'auto');
$moufManager->registerComponent('MoufRepository.php', 'auto');
$moufManager->registerComponent('MoufUtils.php', 'auto');
$moufManager->registerComponent('controllers/PhpInfoController.php', 'auto');
$moufManager->registerComponent('controllers/SearchController.php', 'auto');
$moufManager->registerComponent('actions/InstallUtils.php', 'auto');
$moufManager->registerComponent('load.php', 'auto');

unset($moufManager);

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class MoufAdmin {
	/**
	 * @return TrueCondition
	 */
	 public static function getTrue_condition() {
	 	return MoufManager::getMoufManager()->getInstance('true.condition');
	 }

	/**
	 * @return FalseCondition
	 */
	 public static function getFalse_condition() {
	 	return MoufManager::getMoufManager()->getInstance('false.condition');
	 }

	/**
	 * @return HtmlJSJQuery
	 */
	 public static function getJquery1_6() {
	 	return MoufManager::getMoufManager()->getInstance('jquery-1.6');
	 }

	/**
	 * @return HtmlJSJQueryFixedHeaderTable
	 */
	 public static function getJqueryfixedheadertable1_3() {
	 	return MoufManager::getMoufManager()->getInstance('jquery-fixedheadertable-1.3');
	 }

	/**
	 * @return FinePHPArrayTranslationService
	 */
	 public static function getFineCommonTranslationService() {
	 	return MoufManager::getMoufManager()->getInstance('fineCommonTranslationService');
	 }

	/**
	 * @return HtmlJSJQueryAutoGrow
	 */
	 public static function getJqueryautogrow1_2_2() {
	 	return MoufManager::getMoufManager()->getInstance('jquery-autogrow-1.2.2');
	 }

	/**
	 * @return HtmlJSJQueryUI
	 */
	 public static function getJqueryui() {
	 	return MoufManager::getMoufManager()->getInstance('jquery-ui');
	 }

	/**
	 * @return HtmlJSJQueryFileTree
	 */
	 public static function getJqueryFileTree1_01() {
	 	return MoufManager::getMoufManager()->getInstance('jqueryFileTree-1.01');
	 }

	/**
	 * @return HtmlMenuTopSliderHead
	 */
	 public static function getHtmlMenuTopSliderHead() {
	 	return MoufManager::getMoufManager()->getInstance('htmlMenuTopSliderHead');
	 }

	/**
	 * @return EmailValidator
	 */
	 public static function getEmailValidator() {
	 	return MoufManager::getMoufManager()->getInstance('emailValidator');
	 }

	/**
	 * @return NumberValidator
	 */
	 public static function getNumberValidator() {
	 	return MoufManager::getMoufManager()->getInstance('numberValidator');
	 }

	/**
	 * @return HtmlMenuTopRibbonHead
	 */
	 public static function getHtmlMenuTopRibbonHead() {
	 	return MoufManager::getMoufManager()->getInstance('htmlMenuTopRibbonHead');
	 }

	/**
	 * @return MoufAjaxInstanceController
	 */
	 public static function getAjaxinstance() {
	 	return MoufManager::getMoufManager()->getInstance('ajaxinstance');
	 }

	/**
	 * @return ScriptTagWidget
	 */
	 public static function getChooseInstancePopupJs() {
	 	return MoufManager::getMoufManager()->getInstance('chooseInstancePopupJs');
	 }

	/**
	 * @return ComponentsController
	 */
	 public static function getComponents() {
	 	return MoufManager::getMoufManager()->getInstance('components');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getComponentsSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('componentsSubMenu');
	 }

	/**
	 * @return ConfigController
	 */
	 public static function getConfig() {
	 	return MoufManager::getMoufManager()->getInstance('config');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getConfigCompleteValidator() {
	 	return MoufManager::getMoufManager()->getInstance('configCompleteValidator');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getCreateNewInstanceMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('createNewInstanceMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getCreateNewInstanceMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('createNewInstanceMenuItemIcon');
	 }

	/**
	 * @return WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryManager');
	 }

	/**
	 * @return DefaultWebLibraryRenderer
	 */
	 public static function getDefaultWebLibraryRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryRenderer');
	 }

	/**
	 * @return MoufDisplayGraphController
	 */
	 public static function getDisplayGraph() {
	 	return MoufManager::getMoufManager()->getInstance('displayGraph');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getDisplayPhpInfoMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('displayPhpInfoMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getDisplayPhpInfoMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('displayPhpInfoMenuItemIcon');
	 }

	/**
	 * @return DocumentationController
	 */
	 public static function getDoc() {
	 	return MoufManager::getMoufManager()->getInstance('doc');
	 }

	/**
	 * @return Menu
	 */
	 public static function getDocumentationMenu() {
	 	return MoufManager::getMoufManager()->getInstance('documentationMenu');
	 }

	/**
	 * @return SplashMenuRenderer
	 */
	 public static function getDocumentationMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('documentationMenuRenderer');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getDocumentationSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('documentationSubMenu');
	 }

	/**
	 * @return DownloadPackageAction
	 */
	 public static function getDownloadPackageAction() {
	 	return MoufManager::getMoufManager()->getInstance('downloadPackageAction');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getDownloadPackages2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('downloadPackages2MenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getDownloadPackages2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('downloadPackages2MenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getEditConfigurationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('editConfigurationMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getEditConfigurationMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('editConfigurationMenuItemIcon');
	 }

	/**
	 * @return EnablePackageAction
	 */
	 public static function getEnablePackageAction() {
	 	return MoufManager::getMoufManager()->getInstance('enablePackageAction');
	 }

	/**
	 * @return ErrorLogLogger
	 */
	 public static function getErrorLogger() {
	 	return MoufManager::getMoufManager()->getInstance('errorLogger');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getIncludePhpFilesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('includePhpFilesMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getIncludePhpFilesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('includePhpFilesMenuItemIcon');
	 }

	/**
	 * @return InstallController
	 */
	 public static function getInstall() {
	 	return MoufManager::getMoufManager()->getInstance('install');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getInstallProcessValidator() {
	 	return MoufManager::getMoufManager()->getInstance('installProcessValidator');
	 }

	/**
	 * @return MultiStepActionService
	 */
	 public static function getInstallService() {
	 	return MoufManager::getMoufManager()->getInstance('installService');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public static function getInstallTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('installTemplate');
	 }

	/**
	 * @return MoufInstanceController
	 */
	 public static function getInstance() {
	 	return MoufManager::getMoufManager()->getInstance('instance');
	 }

	/**
	 * @return Menu
	 */
	 public static function getInstanceMenu() {
	 	return MoufManager::getMoufManager()->getInstance('instanceMenu');
	 }

	/**
	 * @return SplashMenuRenderer
	 */
	 public static function getInstanceMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('instanceMenuRenderer');
	 }

	/**
	 * @return HtmlJSJQuery
	 */
	 public static function getJQuery() {
	 	return MoufManager::getMoufManager()->getInstance('jQuery');
	 }

	/**
	 * @return WebLibrary
	 */
	 public static function getJavascript_underscore() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.underscore');
	 }

	/**
	 * @return WebLibrary
	 */
	 public static function getJavascript_underscore_debug() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.underscore.debug');
	 }

	/**
	 * @return HtmlJSJQueryFileTree
	 */
	 public static function getJqueryFileTree() {
	 	return MoufManager::getMoufManager()->getInstance('jqueryFileTree');
	 }

	/**
	 * @return HtmlJSJQueryUI
	 */
	 public static function getJqueryui_0() {
	 	return MoufManager::getMoufManager()->getInstance('jqueryui');
	 }

	/**
	 * @return MoufLoginController
	 */
	 public static function getLogin() {
	 	return MoufManager::getMoufManager()->getInstance('login');
	 }

	/**
	 * @return HtmlString
	 */
	 public static function getLoginWelcomeMessage() {
	 	return MoufManager::getMoufManager()->getInstance('loginWelcomeMessage');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getLogout2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('logout2MenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getLogout2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('logout2MenuItemIcon');
	 }

	/**
	 * @return Menu
	 */
	 public static function getMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('mainMenu');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getManageLocalPackagesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('manageLocalPackagesMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getManageLocalPackagesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('manageLocalPackagesMenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getManageRepositoriesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('manageRepositoriesMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getManageRepositoriesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('manageRepositoriesMenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMiscellaneousSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('miscellaneousSubMenu');
	 }

	/**
	 * @return MoufController
	 */
	 public static function getMouf() {
	 	return MoufManager::getMoufManager()->getInstance('mouf');
	 }

	/**
	 * @return \Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getMoufInstallTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufInstallTemplate');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public static function getMoufInstallTemplate2() {
	 	return MoufManager::getMoufManager()->getInstance('moufInstallTemplate2');
	 }

	/**
	 * @return \Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getMoufLoginTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufLoginTemplate');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMoufStatus2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('moufStatus2MenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getMoufStatus2MenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('moufStatus2MenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMoufSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('moufSubMenu');
	 }

	/**
	 * @return \Mouf\Html\Template\MoufTemplate\MoufTemplate
	 */
	 public static function getMoufTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufTemplate');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getPackageDependenciesValidator() {
	 	return MoufManager::getMoufManager()->getInstance('packageDependenciesValidator');
	 }

	/**
	 * @return MoufPackageDownloadService
	 */
	 public static function getPackageDownloadService() {
	 	return MoufManager::getMoufManager()->getInstance('packageDownloadService');
	 }

	/**
	 * @return PackageController
	 */
	 public static function getPackages() {
	 	return MoufManager::getMoufManager()->getInstance('packages');
	 }

	/**
	 * @return PackageServiceController
	 */
	 public static function getPackagesService() {
	 	return MoufManager::getMoufManager()->getInstance('packagesService');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getPackagesSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('packagesSubMenu');
	 }

	/**
	 * @return PackageDownloadController
	 */
	 public static function getPackagetransfer() {
	 	return MoufManager::getMoufManager()->getInstance('packagetransfer');
	 }

	/**
	 * @return PhpInfoController
	 */
	 public static function getPhpInfo() {
	 	return MoufManager::getMoufManager()->getInstance('phpInfo');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getPhpProjectSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('phpProjectSubMenu');
	 }

	/**
	 * @return HtmlJSPrototype
	 */
	 public static function getPrototype() {
	 	return MoufManager::getMoufManager()->getInstance('prototype');
	 }

	/**
	 * @return RedirectAction
	 */
	 public static function getRedirectAction() {
	 	return MoufManager::getMoufManager()->getInstance('redirectAction');
	 }

	/**
	 * @return RepositorySourceController
	 */
	 public static function getRepositories() {
	 	return MoufManager::getMoufManager()->getInstance('repositories');
	 }

	/**
	 * @return FileCache
	 */
	 public static function getRepositoryCache() {
	 	return MoufManager::getMoufManager()->getInstance('repositoryCache');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getRequiredFilesValidator() {
	 	return MoufManager::getMoufManager()->getInstance('requiredFilesValidator');
	 }

	/**
	 * @return MoufRootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->getInstance('rootController');
	 }

	/**
	 * @return SearchController
	 */
	 public static function getSearch() {
	 	return MoufManager::getMoufManager()->getInstance('search');
	 }

	/**
	 * @return HtmlFromFile
	 */
	 public static function getSearchBox() {
	 	return MoufManager::getMoufManager()->getInstance('searchBox');
	 }

	/**
	 * @return MoufSearchService
	 */
	 public static function getSearchService() {
	 	return MoufManager::getMoufManager()->getInstance('searchService');
	 }

	/**
	 * @return HtmlFromFile
	 */
	 public static function getSetRootUrlJsBlock() {
	 	return MoufManager::getMoufManager()->getInstance('setRootUrlJsBlock');
	 }

	/**
	 * @return Menu
	 */
	 public static function getSpecialActionsMenu() {
	 	return MoufManager::getMoufManager()->getInstance('specialActionsMenu');
	 }

	/**
	 * @return SplashMenuRenderer
	 */
	 public static function getSpecialActionsMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('specialActionsMenuRenderer');
	 }

	/**
	 * @return Splash
	 */
	 public static function getSplash() {
	 	return MoufManager::getMoufManager()->getInstance('splash');
	 }

	/**
	 * @return BrowserLanguageDetection
	 */
	 public static function getSplashBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->getInstance('splashBrowserLanguageDetection');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public static function getSplashTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('splashTemplate');
	 }

	/**
	 * @return FinePHPArrayTranslationService
	 */
	 public static function getSplashTranslateService() {
	 	return MoufManager::getMoufManager()->getInstance('splashTranslateService');
	 }

	/**
	 * @return HtmlJSSyntaxHighlighter
	 */
	 public static function getSyntaxHighlighter() {
	 	return MoufManager::getMoufManager()->getInstance('syntaxHighlighter');
	 }

	/**
	 * @return TopRibbonMenuRenderer
	 */
	 public static function getTopRibbonMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('topRibbonMenuRenderer');
	 }

	/**
	 * @return TopSliderMenuRenderer
	 */
	 public static function getTopSliderMenuRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('topSliderMenuRenderer');
	 }

	/**
	 * @return UserFileDao
	 */
	 public static function getUserFileDao() {
	 	return MoufManager::getMoufManager()->getInstance('userFileDao');
	 }

	/**
	 * @return MoufUserService
	 */
	 public static function getUserService() {
	 	return MoufManager::getMoufManager()->getInstance('userService');
	 }

	/**
	 * @return MoufValidatorController
	 */
	 public static function getValidate() {
	 	return MoufManager::getMoufManager()->getInstance('validate');
	 }

	/**
	 * @return MoufValidatorService
	 */
	 public static function getValidatorService() {
	 	return MoufManager::getMoufManager()->getInstance('validatorService');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getViewDeclaredInstancesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('viewDeclaredInstancesMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getViewDeclaredInstancesMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('viewDeclaredInstancesMenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getViewDocumentationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('viewDocumentationMenuItem');
	 }

	/**
	 * @return MenuItemStyleIcon
	 */
	 public static function getViewDocumentationMenuItemIcon() {
	 	return MoufManager::getMoufManager()->getInstance('viewDocumentationMenuItemIcon');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getHtmlMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('htmlMainMenu');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getHtmlFineMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineMainMenu');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getHtmlFineEditTranslationMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineEditTranslationMenuItem');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getHtmlFineEditTranslationAnyInstanceMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineEditTranslationAnyInstanceMenuItem');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getHtmlFineSupportedLanguagesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineSupportedLanguagesMenuItem');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getHtmlFineEnableDisable2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineEnableDisable2MenuItem');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getHtmlFineImportCSV2MenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('htmlFineImportCSV2MenuItem');
	 }

	/**
	 * @return EditLabelController
	 */
	 public static function getEditLabels() {
	 	return MoufManager::getMoufManager()->getInstance('editLabels');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getUtilsMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('utilsMainMenu');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getUtilsCacheInterfaceMenu() {
	 	return MoufManager::getMoufManager()->getInstance('utilsCacheInterfaceMenu');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getUtilsCacheInterfacePurgeAllCachesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('utilsCacheInterfacePurgeAllCachesMenuItem');
	 }

	/**
	 * @return PurgeCacheController
	 */
	 public static function getPurgeCaches() {
	 	return MoufManager::getMoufManager()->getInstance('purgeCaches');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMvcMainMenu() {
	 	return MoufManager::getMoufManager()->getInstance('mvcMainMenu');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMvcSplashSubMenu() {
	 	return MoufManager::getMoufManager()->getInstance('mvcSplashSubMenu');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMvcSplashAdminUrlsListMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('mvcSplashAdminUrlsListMenuItem');
	 }

	/**
	 * @return SplashViewUrlsController
	 */
	 public static function getSplashViewUrls() {
	 	return MoufManager::getMoufManager()->getInstance('splashViewUrls');
	 }

	/**
	 * @return SplashGenerateService
	 */
	 public static function getSplashGenerateService() {
	 	return MoufManager::getMoufManager()->getInstance('splashGenerateService');
	 }

	/**
	 * @return SplashAdminApacheConfigureController
	 */
	 public static function getSplashApacheConfig() {
	 	return MoufManager::getMoufManager()->getInstance('splashApacheConfig');
	 }

	/**
	 * @return SplashInstallController
	 */
	 public static function getSplashinstall() {
	 	return MoufManager::getMoufManager()->getInstance('splashinstall');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getSplashHtaccessValidator() {
	 	return MoufManager::getMoufManager()->getInstance('splashHtaccessValidator');
	 }

	/**
	 * @return MenuItem
	 */
	 public static function getMvcSplashAdminApacheConfig2Item() {
	 	return MoufManager::getMoufManager()->getInstance('mvcSplashAdminApacheConfig2Item');
	 }

}
?>
