<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */

// Files declared in the extra:mouf:adminRequire section.
require_once __DIR__.'/../vendor/mouf/security.userservice/src/MoufUserServiceValidators.php';
require_once __DIR__.'/../vendor/mouf/utils.cache.cache-interface/CacheAdmin.php';

?>