<?php
/*
 * This file is part of the Mouf core package.
 *
 * (c) 2012 David Negrier <david@mouf-php.com>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */
 
/**
 * This file is used to install the Mouf framework by creating the .htaccess file.
 */

$uri = $_SERVER["REQUEST_URI"];

$installPos = strpos($uri, "/install.php");
if ($installPos !== FALSE) {
	$uri = substr($uri, 0, $installPos);
}


$str = "Options FollowSymLinks
RewriteEngine on
RewriteBase $uri

#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule mouf\\/doc\\/view\\/ splash.php
RewriteRule !((\\.(js|ico|gif|jpg|png|css)$)|^direct) splash.php";

file_put_contents(".htaccess", $str);


// Now, let's write the basic Mouf files:
// Write Mouf.php:
if (!file_exists("../Mouf.php")) {
	$moufStr = "<?php
require_once 'MoufComponents.php';
require_once 'MoufUniversalParameters.php';
require_once 'config.php';
require_once 'MoufRequire.php';
?>";
	
	file_put_contents("../Mouf.php", $moufStr);
}



// Write MoufComponents.php:
if (!file_exists("../MoufComponents.php")) {
	$moufComponentsStr = "<?php
	/**
	 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
	 */
	require_once 'mouf/MoufManager.php';
	MoufManager::initMoufManager();
	\$moufManager = MoufManager::getMoufManager();

	\$moufManager->setAllVariables(array (
	  'repositoryUrls' => 
	  array (
		0 => 
		array (
		  'name' => 'mouf',
		  'url' => 'http://mouf-php.com/mouf',
		),
	  ),
	));
	?>";
	
	file_put_contents("../MoufComponents.php", $moufComponentsStr);
}

// Write MoufUniversalParameters.php
if (!file_exists("../MoufUniversalParameters.php")) {
	$uriWithoutMouf = substr($uri, 0, -4);
	$moufUniversalStr = "<?php
	
	define('ROOT_PATH', realpath(dirname(__FILE__)).DIRECTORY_SEPARATOR);
	define('ROOT_URL','".$uriWithoutMouf."');
	define('PLUGINS_URL',ROOT_URL.'plugins/');
	?>";
	
	file_put_contents("../MoufUniversalParameters.php", $moufUniversalStr);
}

// Let's generate the MoufRequire.php file:
if (!file_exists("../MoufRequire.php")) {
	$moufRequireStr = "<?php
	/**
	 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
	 */
	
	?>";
	
	file_put_contents("../MoufRequire.php", $moufRequireStr);
}

// Finally, let's generate the MoufUI.php file:
if (!file_exists("../MoufUI.php")) {
	$moufUIStr = "<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
	
	?>";
	
	file_put_contents("../MoufUI.php", $moufUIStr);
}

// Finally 2, let's generate the config.php file:
if (!file_exists("../config.php")) {
	$moufConfig = "<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 * Use the UI to edit it instead.
 */
	
	?>";
	
	file_put_contents("../config.php", $moufConfig);
}

// Finally 3 :), let's generate the MoufUsers.php file:
if (!file_exists("../MoufUsers.php")) {
	$moufConfig = "<?php
/**
 * This contains the users allowed to access the Mouf framework.
 */
\$users[".var_export(install_userinput_to_plainstring($_REQUEST['login']), true)."] = array('password'=>".var_export(sha1(install_userinput_to_plainstring($_REQUEST['password'])), true).", 'options'=>null);
	
	?>";
	
	file_put_contents("../MoufUsers.php", $moufConfig);
}

// Finally 4, let's generate the config.php file for the mouf directory:
if (!file_exists("config.php")) {
	$moufConfig = "<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 * Use the UI to edit it instead.
 */

/**
 * If you set this variable to true, your Mouf installation will act as a repository: it will allow other Mouf installations to download any package available.
 * By default, this is behaviour is disabled.
 */
define('ACT_AS_REPOSITORY', true);
 
	?>";
	
	file_put_contents("../config.php", $moufConfig);
}

function install_userinput_to_plainstring($str) {
	if (get_magic_quotes_gpc()==1)
	{
		$str = stripslashes($str);
		// Rajouter les slashes soumis par l'utilisateur
		//$str = str_replace('\\', '\\\\', $str);
		return $str;
	}
	else
		return $str;
}


header("Location: ".$uri."/");

?>
